### ISSUE TITLE
Change Kenneth Reitz RSS URL

### ISSUE THREAD

**Issue by kennethreitz** [python/planet#104]
Hello,

The following URL should be used for my contributions to Planet Python:

`http://www.kennethreitz.org/?category=Development&format=rss`

Many thanks :)

**Comment by berkerpeksag** [comment]
Done. It should be online in an hour or so.

**Comment by kennethreitz** [comment]
@berkerpeksag :sparkles: :cake: :sparkles:

**Comment by kennethreitz** [comment]
Hmm, this doesn't seem to be working.

**Comment by kennethreitz** [comment]
I think it's on my end. Will update when I figure it out.

**Comment by kennethreitz** [comment]
e.g. this url was returning an RSS feed, and no longer is. Frustrated with Squarespace :)
