### ISSUE TITLE
Add my blog feed to Planet Python

### ISSUE THREAD

**Issue by alstat** [python/planet#11]
Hi, I want to join Planet Python. I am the owner of the Analysis with Programming blog, and I write post about Statistical Analysis using programming which includes Python language. I would really appreciate if you could include my blog feed on your site:

http://alstatr.blogspot.com/feeds/posts/default/-/Python

Thank you!

**Comment by tseaver** [comment]
Your feed should show up in the next update (no more than a few hours).
