### ISSUE TITLE
Feed parsing issue?

### ISSUE THREAD

**Issue by ionelmc** [python/planet#110]
I have published a new post in my feed (https://blog.ionelmc.ro/feeds/python.atom.xml) and I don't see anything in the planed feed but other newer posts (from other people appear).

I have switched to ssl recently. Is there anything wrong it the setup?

**Comment by ionelmc** [comment]
I have disabled the redirect to https for now but I'd still like to know what's wrong.

**Comment by tseaver** [comment]
I can't see why there would be any issue.  We don't have access to the logs created during the update cycle, which makes debugging after-the-fact hard.  I will leave this issue open, hoping that the problem corrects itself after our change.  Please ping me if it doesn't.

**Comment by ionelmc** [comment]
>  our change

Did you change something or you mean my change?

**Comment by tseaver** [comment]
I meant your change.

**Comment by ionelmc** [comment]
Seems it's fine now. Thanks.
