### ISSUE TITLE
My feed isn't working

### ISSUE THREAD

**Issue by treyhunner** [python/planet#114]
I submitted #113 thinking it as an HTTP/HTTPS issue, but it looks like the last article I published in my feed still isn't appearing on the Planet Python feed.

Any way I can help troubleshoot what might be going on?

**Comment by rochacbruno** [comment]
@treyhunner http://feedvalidator.org/check.cgi?url=http%3A%2F%2Ftreyhunner.com%2Fpython.xml

**Comment by rochacbruno** [comment]
Looks like there is a bug in OpenSSL https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137 and then feedreaders cant access HTTPS feeds using openssl

**Comment by treyhunner** [comment]
Thanks @rochacbruno. I disabled forced HTTPS so now both HTTP and HTTPS work for accessing my site (which is a little odd but that seems to fix the validation on HTTP at least).
