### ISSUE TITLE
Remove Future Foundries, add Code Without Rules

### ISSUE THREAD

**Issue by itamarst** [python/planet#117]
1. Future Foundries link is now defunct, as we've shut down the company (couple years ago actually).
2. I am however now blogging at http://codewithoutrules.com - feed at http://codewithoutrules.com/atom.xml

Thanks!

**Comment by rochacbruno** [comment]
Hi @itamarst so you have a Python specific feed to provide?

**Comment by itamarst** [comment]
The content is mostly generic software engineering-y, though I tend to use Python by default for examples as in http://codewithoutrules.com/2016/03/01/process-reminders/ (scroll down a bit). So perhaps blog is not suitable? Or are there specific posts on the feed you think are OK and some that aren't, so I can filter appropriately?

**Comment by itamarst** [comment]
I'm happy to make filtered feed, to be clear, just want a sense if you feel generic software engineering is irrelevant. I've been part of Python community since 2000, so it's just my default place to share things, but I also don't want to spam people or post inappropriate content.

**Comment by rochacbruno** [comment]
@itamarst Engineering is very relevant! but in planet Python we try to filter Python specific posts only, example: if in your general engineering post you talk about something that can be applied using Python, you put a "python" tag in the post. And them we add the Python tag feed to the planet.

Does your blogging platform has some kind of tagging or categorization for feeds?

**Comment by itamarst** [comment]
Pretty sure it's possible, but will need to be setup manually. I'll see about adding one and link it here. Thanks!

**Comment by itamarst** [comment]
OK, here's a Python-specific feed: http://codewithoutrules.com/python-atom.xml

**Comment by rochacbruno** [comment]
Almost there, there is still a little problem, your feed doesn't validate

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fcodewithoutrules.com%2Fpython-atom.xml

```
Sorry

This feed does not validate.

line 11, column 10: email must be an email address: [help]

   <email></email>
          ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 5, column 67: Self reference doesn't match document location [help]

 <link href="http://www.codewithoutrules.com/atom.xml" rel="self"/>
                                                                   ^
line 8, column 36: Identifier "http://www.codewithoutrules.com" is not in canonical form (the canonical form would be "http://www.codewithoutrules.com/") [help]

 <id>http://www.codewithoutrules.com</id>
                                    ^
line 63, column 0: content should not contain data-lang attribute (3 occurrences) [help]

&lt;figure class=&quot;highlight&quot;&gt;&lt;pre&gt;&lt;code class=&quot;la ...
```

**Comment by itamarst** [comment]
OK, should validate now (still some warnings, but not clear how to fix them and they don't seem critical, I hope?). Thanks!
