### ISSUE TITLE
Add pgcli blog to planet python

### ISSUE THREAD

**Issue by amjith** [python/planet#12]
Feed: http://pgcli.com/feeds/blog.atom.xml

`pgcli` is an open-source postgres command line tool with auto-completion and syntax highlighting. It is written in Python. 

The blog on http://pgcli.com will be used to describe the features, release announcements, changelog etc.

**Comment by tseaver** [comment]
It is hard to tell from only a single article:  will the whole feed be relevant to Planet Python?  If not, could you give us a feed URL for a `python` category, where only such posts would have that tag?

**Comment by amjith** [comment]
Fair point. Although I don't plan on blogging about anything else but pgcli, I'll create a tag feed for python.

I'll update this issue once I have the feed ready. Thanks!

**Comment by amjith** [comment]
I've created a feed for python specific tag. 

http://pgcli.com/feeds/tag.python.atom.xml

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (a few hours or so).
