### ISSUE TITLE
Dozens of appearances of the same post featuring an annoying budgie

### ISSUE THREAD

**Issue by jwg4** [python/planet#121]
Hi, I have seen a post from Galvanize, appear several times a day in our feed. The post may now be removed since it publicizes an event which happened yesterday. However, it seems like that blog is doing something to spam their content (featuring a quite annoying picture of a man with a budgie on his shoulder) again and again, pushing other things up the scroll.

We are using the Slack RSS integration.

The post in question is at http://www.galvanize.com/event/seattle-data-science-workshop-writing-elegant-and-efficient-python/#.VuBpY-aHjOU

I really hope that if they are doing this intentionally they can be prevented, and if they are doing it accidentally they can stop (and not start again next time they are publicizing an event).

**Comment by tseaver** [comment]
That post is only appearing once in the Planet feed (although it is out-of-date).  Not much we can do from here, except to drop the feed entirely if the bug / abuse continues.

**Comment by jwg4** [comment]
There is another issue, https://github.com/python/planet/issues/97 about someone who was repeatedly pushing their post to the top of the feed. Perhaps this interacts with certain feed readers, which assume that this hasn't been done, and causes the repeat appearances?
