### ISSUE TITLE
Please Add My Feed.

### ISSUE THREAD

**Issue by allanderek** [python/planet#126]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Coding Diet

**My Blog RSS or ATOM Python specific feed url**: http://allanderek.github.io/categories/python.xml
 
## I checked the following required validations: (mark all 4 with [x])

1. [x ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [ x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tjguk** [comment]
Thanks; should appear in the next update
