### ISSUE TITLE
sort-ini should sort by name?

### ISSUE THREAD

**Issue by rochacbruno** [python/planet#128]
# INFORM A BUG/PROBLEM

---

Hi, I want to notify you of a bug/problem that is happening on the Planet.
## Problem

the command `python sort-ini.py` is grouping by URL which causes the entries to be grouped by https and https, + www and naked.

Maybe it needs to sort by name?

ini file: https://github.com/python/planet/blob/master/config/config.ini

sort script: https://github.com/python/planet/blob/master/config/sort-ini.py

**Comment by AnshulMalik** [comment]
I think that's right, it should sort not take https or www in consideration.
