### ISSUE TITLE
Add feed PyCon Australia 2016 news

### ISSUE THREAD

**Issue by pfctdayelise** [python/planet#129]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: PyCon Australia 2016 news

**My Blog RSS or ATOM Python specific feed url**: https://2016.pycon-au.org/media/news/rss
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://2016.pycon-au.org/media/news/rss and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle (an hour or two).
