### ISSUE TITLE
Add Eniram Developers' Blog

### ISSUE THREAD

**Issue by akaihola** [python/planet#13]
http://eniramltd.github.io/devblog/rss/categories/python.xml

This a feed which contains blog posts from the Python category, written by members of development teams at [Eniram Ltd](http://www.eniram.fi/).

Currently we're running a series of posts about dataflow programming in Python, related to our [presentation](http://fi.pycon.org/2014/#talks-lusmu) last October in [PyCon Finland 2014](http://fi.pycon.org/2014/). There's also a post about geodetic distance calculations.

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (a few hours or so).
