### ISSUE TITLE
To add my feed to python planet.

### ISSUE THREAD

**Issue by Pulkit07** [python/planet#133]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**Pulkit Goyal**: MY_NAME

**Programmers Blog**: BLOG_NAME_HERE  

**http://pulkitgoyal.com/rss.xml**: MY_FEED_URL  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by rochacbruno** [comment]
@Pulkit07 you feed url is too much generic, is it safe that your are going to post only Python related content to your blog? don't you have a tag or category filtered url?

**Comment by Pulkit07** [comment]
Well the sections Algorithms and Machine learning will only involve concepts, moreover my main writing will be about GSoC project, which is under Mercurial, well I agree only and just python stuffs can be violated.
