### ISSUE TITLE
Add feed for cobe.io/blog/categories/python/

### ISSUE THREAD

**Issue by flub** [python/planet#136]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Cobe.io 

**My Blog RSS or ATOM Python specific feed url**: https://cobe.io/blog/categories/python.xml
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://cobe.io/blog/categories/python.xml and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

This is a blog for a commercial organisation, however I believe this is accepted for relevant content.  The current 3 posts on that category are a realistic sample of the sort of content we would publish under the python tag.  Please let us know if that is reasonable or if we need to tweak which content we post with the python tag.

Thanks in advance for adding the feed to the PythonPlanet! :+1:

**Comment by tjguk** [comment]
Thanks; should appear at the next update (usually a few hours)
