### ISSUE TITLE
Please add tryexceptpass medium posts

### ISSUE THREAD

**Issue by tryexceptpass** [python/planet#138]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: @tryexceptpass (e.g John Doe Awesome Blog)  

**My Blog RSS or ATOM Python specific feed url**: https://www.medium.com/feed/@tryexceptpass  
 
## I checked the following required validations: (mark all 4 with [x])

1. [ X ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [ X ] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ X ] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [ X ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle (an hour or so, usually).
