### ISSUE TITLE
Add 'Petecode' blog

### ISSUE THREAD

**Issue by wearpants** [python/planet#144]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Petecode  

**My Blog RSS or ATOM Python specific feed url**: https://wearpants.org/feeds/petecode.xml?tag=python  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle (an hour or so, usually).

**Comment by wearpants** [comment]
thanks so much!

On Tue, Jun 7, 2016 at 4:09 PM, Tres Seaver <notifications@github.com>
wrote:

> Your feed should appear in the next update cycle (an hour or so, usually).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/planet/issues/144#issuecomment-224398556>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAe2AIGTMszS6ddydvkwHX4H64Qf7RvUks5qJc_cgaJpZM4IwRRQ>
> .
>



-- 
Pete Fein | wearpants.org | @wearpants
