### ISSUE TITLE
Please Add "pythonwise" Blog

### ISSUE THREAD

**Issue by tebeka** [python/planet#150]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: pythonwise (e.g John Doe Awesome Blog)  

**My Blog RSS or ATOM Python specific feed url**: http://pythonwise.blogspot.com/feeds/posts/default  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
@tebeka The content in that feed seems less Python-focused than the Planet prefers.  Can you please tag the Python-related posts and post a feed URL which selects them?

**Comment by tebeka** [comment]
Sure. Will do when back.

**Comment by tebeka** [comment]
Added `python` label to latest post, the feed is http://www.pythonwise.blogspot.com/feeds/posts/default/-/python

I'll go and label older posts as I go

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle (an hour or so, usually).

**Comment by tebeka** [comment]
Thanks!
