### ISSUE TITLE
Add feed to planet Python

### ISSUE THREAD

**Issue by morphex** [python/planet#154]
Hi, I want to add my feed to the Python Planet.

The blog name is "Morphex's Blogologue"

The feed is here: http://blogologue.com/atom.xml?category=1470141490X3

My feed is valid, checked it on W3C.  

It is Python specific.

I only post content of interest to the Python community here.

I understand that it can take some time for the feed to be included on PPO.
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed (which has no posts as of now) will appear in the next update cycle (an hour or so, usually).

**Comment by morphex** [comment]
Alright, thanks for the tip. Feed is in order now.
