### ISSUE TITLE
Orbited feed doesn't seem to be Python related

### ISSUE THREAD

**Issue by The-Compiler** [python/planet#166]
Orbited (which was added in d7136a93137326d7f65f4bacf0942fe63ea7025d) was probably hijacked and doesn't look Python related at all: http://www.orbited.org/

The post "[Ideas to throw the best birthday parties for your children](http://www.orbited.org/ideas-to-throw-the-best-birthday-parties-for-your-children/)" just appeared on the planet FWIW.

cc @mfoord

**Comment by tseaver** [comment]
@The-Compiler Thanks for reporting the issue!  I have just removed the feed from the planet config:  it should disappear in the next update cycle.
