### ISSUE TITLE
Add my blog to Planet Python

### ISSUE THREAD

**Issue by gbtami** [python/planet#17]
Hi! I want to join to Planet Python.
My feed is here http://gbtami.github.io/feed.xml

**Comment by tseaver** [comment]
I've looked at the feed:  based on the with only a single article to date, it is a little hard to tell if the focus of the blog is all Python.  I will add it as is, but we may need to switch to a "category" / "tag" feed in the future.

**Comment by gbtami** [comment]
Switched to http://gbtami.github.io/feed.python.xml
Thx!

**Comment by tseaver** [comment]
Updated in 832f07828fcc8cfb0df5d608859f81035b51aacc
