### ISSUE TITLE
Feed getting published again

### ISSUE THREAD

**Issue by originalankur** [python/planet#171]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**:  Linux
**Browser**:  Firefox
**Platform**: (mobile, tablet, desktop)  desktop

## Problem
The feed of my blog http://importpython.com/blog/ was getting updated again and again due to publish date being datetime.datetime.now() , this bug creeped in due to testing code that made it to production and live site. This problem was reported by a user I have taken the feed down until I fix it. This ticket is to reach out to the maintainers of the project, I apologie for the problem. I am fixing it. 

Thanks.

**Comment by originalankur** [comment]
I have taken the feed down as I fix the problem.

**Comment by tjguk** [comment]
Thanks for letting us know
