### ISSUE TITLE
Please add 'My thoughts and learnings' blog

### ISSUE THREAD

**Issue by duttashi** [python/planet#174]
Hi, 

I want to add my blog feed to the Python Planet.

My Name/Blog Name: My thoughts and learnings

My Blog RSS or ATOM Python specific feed url: http://feeds.feedburner.com/PythonMyThoughtsLearnings

I checked the following required validations: (mark all 4 with [x])

[ X ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=http://feeds.feedburner.com/PythonMyThoughtsLearnings and it is valid!
[ X ] My feed is a Python Specific feed, e.g: I am proposing the filtered tag or categorized feed url
[ X ] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
[ X ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my blog feed to the PythonPlanet!

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.
