### ISSUE TITLE
Update for willmcgugan.com

### ISSUE THREAD

**Issue by willmcgugan** [python/planet#19]
Hi,

My feed was broken for a while, and it looks like it was disabled on planetpython.org. Would you mind re-enabling it?

http://www.willmcgugan.com/blog/tech/feeds/posts/

Regards,

Will McGugan

**Comment by tseaver** [comment]
Your new feed URL should be picked up in the next update cycle (a few hours or so).

**Comment by willmcgugan** [comment]
Great. Thanks!
