### ISSUE TITLE
codementor.io constantly republishes stuff

### ISSUE THREAD

**Issue by vincentbernat** [python/planet#190]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

## Problem
codementor.io posts are constantly pushed at the top of the feed. This has already been signaled in #97 but I only noticed this during last week. Looking directly at their [feed](https://www.codementor.io/python/tutorial/feed/), I see:

```xml
<title type="html">Using Docker and Docker Compose for Local Development and Small Deployments</title>
<link rel="alternate" href="https://www.codementor.io/jquacinella/tutorials/docker-and-docker-compose-fo
r-local-development-and-small-deployments-ph4p434gb"/>
<id>tag:www.codementor.io,2014:tutorial:1341</id>
<updated>2017-01-01T20:02:49Z</updated>
<published>2016-12-21T07:07:28Z</published>
```

So maybe, the problem is with the Planet using `updated`?

cc @alpaca-power

**Comment by tseaver** [comment]
Via #191.

**Comment by vincentbernat** [comment]
Thanks!

**Comment by tseaver** [comment]
#192 restores the feed for Codementor, now that it correctly sets per-item `<updated>`.
