### ISSUE TITLE
OPML feed doesn't match URL in config.ini

### ISSUE THREAD

**Issue by brettcannon** [python/planet#193]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

## Problem
http://planetpython.org/opml.xml does not have feed URLs that exactly match https://github.com/python/planet/blob/master/config/config.ini.

## Details
If you look at https://github.com/python/planet/blob/master/config/config.ini you will notice that I have a feed at https://snarky.ca/rss/. But if you look at http://planetpython.org/opml.xml you will notice the feed is listed as http://snarky.ca/rss/ (so not HTTPS).

I wrote a new post today and it has not shown up on the Planet and I'm wondering if it has to do with the fact that I have a general HTTP -> HTTPS forwarding rule and Planet is simply not following the forward.

Thanks.

**Comment by brettcannon** [comment]
I should also mention that [my feed is valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsnarky.ca%2Frss%2F).

**Comment by Mariatta** [comment]
This is still a problem for @brettcannon , but I don't know how to fix it :(
Anyone has any ideas? :sweat_smile:

**Comment by brettcannon** [comment]
Re-implement Planet in Python 3. 😉

**Comment by MarkMangoba** [comment]
@mfoord and @tseaver any thoughts on this?

**Comment by brettcannon** [comment]
This is still an issue: wrote a post yesterday and it never showed on the feed.

**Comment by Mariatta** [comment]
Pinging this again. This is also affecting @pydanny in GH-219

**Comment by pydanny** [comment]
My current problem is that my blog won't generate RSS that passes the W3C validator. And Pelican's migration system is pretty awful so I had to revert to my legacy version. And I don't have time to upgrade to a new blog.

On the bright side, EVERYWHERE else that consumes my blog's RSS feed is fine with the XML my blog supplies. Which makes me wonder, what's the point of validating tightly something like RSS which doesn't have a single universal specification?

**Comment by ewdurbin** [comment]
@brettcannon I believe this should be resolved with the update that was applied today for TLS feeds.

**Comment by ewdurbin** [comment]
confirmed:

before:

```
>>> from planet import feedparser
>>> feedparser.parse('https://snarky.ca/rss/')
{'feed': {}, 'encoding': 'utf-8', 'bozo': 1, 'version': None, 'entries': [], 'bozo_exception': URLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),)}
```

after:

```
>>> from planet import feedparser
>>> feedparser.parse('http://snarky.ca/rss/')
{'feed': {'lastbuilddate': u'Thu, 02 Aug 2018 15:55:24 GMT', 'subtitle': u'Python core developer. Dev lead for the Python extension for VS Code. Tall, snarky Canadian.', 'generator': u'Ghost 1.25', 'links': [{'href': u'https://snarky.ca/', 'type': 'text/html', 'rel': 'alternate'}, {...
```

**Comment by brettcannon** [comment]
@ewdurbin thanks! I'll keep an eye out to see if my next post gets picked up.
