### ISSUE TITLE
Add feed for my blog

### ISSUE THREAD

**Issue by oa** [python/planet#201]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Oliver Andrich

**My Blog RSS or ATOM Python specific feed url**: https://andrich.blog/tag/python/feed/
 
## I checked the following required validations: (mark all 4 with [x])

1. [X] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tjguk** [comment]
Should appear at the next refresh (usually a few hours)

**Comment by oa** [comment]
Why does the planet only show "shortened articles" and not the full content? My feed contains the full content, but only the "summary" or description is used. Any hint, what I can do to fix this?
