### ISSUE TITLE
Add python blog of Eray Ozkural, please :)

### ISSUE THREAD

**Issue by examachine** [python/planet#203]
Hi, I want to add my feed to the Python Planet.

Eray Özkural (examachine)

https://examachine.net/blog/category/python/feed/

1. [X ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://github.com/examachine/pisi and it is valid!
2. [ X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

I am the main author of PISI, a package manager written fully in python: 
https://github.com/examachine/pisi

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.
