### ISSUE TITLE
Please add Python Bytes podcast to your feed

### ISSUE THREAD

**Issue by mikeckennedy** [python/planet#205]
!!! Please choose one template below ADD FEED, EDIT FEED or INFORM a BUG/PROBLEM.
PLEASE: Remove this headline and the unused templates!!!

# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Python Bytes

**My Blog RSS or ATOM Python specific feed url**: https://pythonbytes.fm/episodes/rss
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://pythonbytes.fm/episodes/rss and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by rochacbruno** [comment]
Hi @mikeckennedy 

Sorry, This feed does not validate.

https://validator.w3.org/feed/check.cgi?url=https://pythonbytes.fm/episodes/rss

**Comment by mikeckennedy** [comment]
Hi @rochacbruno 

Thanks for checking this out. It does not validate but ONLY for iTunes. Does Planet Python only accept RSS feeds for podcasts (granted this is one...). I thought it was a general blog aggregator. Let me know if I missed one of the validation errors. For a general blog I think it's valid.

But I will go and trim back the keyword count and such. That wasn't a problem when I created the site but apparently is after it's been out.

Best,
Michael

**Comment by mikeckennedy** [comment]
Did you notice that some of these are just errors on the validator's side? For example, this error:

**url must be a full URL**:

`https://pythonbytes.fm/episodes/download/24/i-have-a-local-pypi-server-and-so-do-you.mp3`

Sure looks like a full URL to me.

**Comment by mikeckennedy** [comment]
This error makes no sense:

**line 3980, column 3: description should not contain relative URL references: matplotlib.org [help]**

`<li><a href="http://matplotlib.org/">matplotlib.org</a></li>`

That is also a full URL. And so on.

**Comment by rochacbruno** [comment]
@mikeckennedy ok, you are right. I used this other validator specific for podcast feeds http://castfeedvalidator.com/?url=https://pythonbytes.fm/episodes/rss and it hows as valid.

I guess w3c validator does not accept itunes tags.

**Comment by rochacbruno** [comment]
Done!

Will be fetched soon in the next server update cycle.

Thanks and welcome to Python Planet.

**Comment by mikeckennedy** [comment]
Thanks a bunch @rochacbruno !
