### ISSUE TITLE
Please add Techiediaries feed to Planet Python 

### ISSUE THREAD

**Issue by techiediaries** [python/planet#213]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Techiediaries

**My Blog RSS or ATOM Python specific feed url**: https://www.techiediaries.com/django/feed.xml
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://www.techiediaries.com/django/feed.xml and it is valid!

2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.

**Comment by techiediaries** [comment]
Hi ,
I'm sorry but the feed of my website doesn't appear of planet python even if the name of the website is in the list of added feeds but the feed is not fetched

**Comment by tseaver** [comment]
@techiediaries The feed is failing to fetch with the following error:

> SSLError(1, '_ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error')

Can you help diagnose?
