### ISSUE TITLE
Update feed for Podcast.__init__

### ISSUE THREAD

**Issue by blarghmatey** [python/planet#214]
# EDIT FEED
------------------------------------------------------------------------------
Hi, I want to change my current feed url from http://podcastinit.podbean.com/feed to https://www.podcastinit.com/feed/mp3/

## I checked the following required validations:  (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://www.podcastinit.com/feed/mp3/ and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for changing my feed on Python Planet! :+1:

**Comment by tseaver** [comment]
Hmm, that validation page says the feed does not validate, although I confess I can't see what is wrong.

**Comment by blarghmatey** [comment]
Yeah, from what I was able to gather most of it is because I'm using HTTPS instead of just HTTP for all of the URLs.

**Comment by tseaver** [comment]
The updated feed URL should appear in the next cron-driven cycle.
