### ISSUE TITLE
Request to add Djangostars blog to the feed

### ISSUE THREAD

**Issue by Yaroslavle** [python/planet#216]
Hi! We writing a lot about python and django - different educational articles and tutorials like "How to start with Docker using python"

**My Blog RSS: http://djangostars.com/blog/category/python/rss/
 
I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=http://djangostars.com/blog/category/python/rss/ and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.

**Comment by Yaroslavle** [comment]
Thank you!
