### ISSUE TITLE
Edit codementor.io feed URL

### ISSUE THREAD

**Issue by joycelee11** [python/planet#226]
# EDIT FEED
Hi, I want to change my current feed url from https://www.codementor.io/python/tutorial/feed/ to https://www.codementor.io/community/topic/python/feed

## I checked the following required validations:

1. [X] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for changing my feed on Python Planet! :+1:

**Comment by tseaver** [comment]
Your updated feed will appear in the next refresh cycle.

**Comment by joycelee11** [comment]
Thanks so much!

**Comment by tseaver** [comment]
@joycelee11 The CodeMentor feed is spewing lots ot non-Python-related articles into PlanetPython.  Can you please investigate?  We will need to remove the feed (again!) if you cannot remediate this issue.

**Comment by tseaver** [comment]
@joycelee11 Please see PR #241, which removes the CodeMentor feed from the planet.  I will merge it tomorrow unless the feed corrects itself.

**Comment by joycelee11** [comment]
@tseaver Thanks for the heads up. We refactored part of our API yesterday and missed this. We're working on a fix right now.

**Comment by joycelee11** [comment]
@tseaver We've just deployed a fix for the feed. Please check!

**Comment by tseaver** [comment]
@joycelee11 Looks like the fix propagated.  Thanks!
