### ISSUE TITLE
Edit My RSS FEED [Previous One Not Working with Python Planet !!!]

### ISSUE THREAD

**Issue by techiediaries** [python/planet#232]
# EDIT FEED
------------------------------------------------------------------------------
Hi, I want to change my current feed url from https://www.techiediaries.com/django/feed.xml  to https://www.techiediaries.com/tag/django/index.xml 

## I checked the following required validations:  (mark all 4 with [x])

1. [x ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://www.techiediaries.com/tag/django/index.xml  and it is valid!
2. [x ] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for changing my feed on Python Planet! :+1:

**Comment by rochacbruno** [comment]
Done!

Will be fetched soon in the next server update cycle.
