### ISSUE TITLE
Add breadcrumbscollector.tech blog (Python Only Posts)

### ISSUE THREAD

**Issue by Enforcer** [python/planet#234]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: BreadcrumbsCollector

**My Blog RSS or ATOM Python specific feed url**: https://breadcrumbscollector.tech/category/python/feed/
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://breadcrumbscollector.tech/category/python/feed/ and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
The feed is empty, which makes it hard to evaluate that the "Python-only" bit is actually working.  Looking at the [main page for the site](https://breadcrumbscollector.tech/), it appears that there are a number of articles which would be taggable as Python-related.

**Comment by Enforcer** [comment]
I am confused, there are 7 posts in the category so far. Various feed readers can get them all, for example:
http://carp.docs.geckotribe.com/feed-test.php?feed=https%3A%2F%2Fbreadcrumbscollector.tech%2Fcategory%2Fpython%2Ffeed%2F

http://castfeedvalidator.com/?url=https://breadcrumbscollector.tech/category/python/feed/

Can you please provide any more info? Is there a problem with SSL maybe, so it returns blank page?

**Comment by tseaver** [comment]
Maybe it was a transient error.  I can see articles now.
