### ISSUE TITLE
SSL errors on otherwise valid xml feed

### ISSUE THREAD

**Issue by pybites** [python/planet#240]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**:  Mac
**Browser**:  Chrome
**Platform**: (mobile, tablet, desktop)  desktop

## Problem
tseaver confirmed error: 
SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

## Details
As confirmed in https://github.com/python/planet/pull/239 both feedparser 4.1 and 5.2 throw ssl errors in python 2.x: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

This could solve it but feels like a hack

import ssl
# https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
ssl._create_default_https_context = ssl._create_unverified_context

This probably happens for more feeds. 

Thanks.

**Comment by treyhunner** [comment]
This issue affected me a couple years ago: #114.

This issue has been holding me back from switching my website to HTTPS for years now. It would be absolutely lovely to embrace the wonders of SSL one day! Let me know if there's anything I can do to help move this along. 💖

**Comment by ewdurbin** [comment]
Fetching modern TLS'd feeds has been resolved.

**Comment by bbelderbos** [comment]
Awesome! Thanks a ton
