### ISSUE TITLE
Please Add My Blog Feed To Planet Python

### ISSUE THREAD

**Issue by techiediaries** [python/planet#243]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Techiediaries  

**My Blog RSS or ATOM Python specific feed url**: https://techiediaries.github.io/atom.xml  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://techiediaries.github.io/atom.xml and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Can you please give us a URL for a Python-specific tag / category?  Given that there is only the one post now, I'm basing this request on the content of the @techiediaries twitter feed, which contains many non-Python-related tweets.

**Comment by techiediaries** [comment]
I'm going to write only Python/Django specific posts in this blog. If otherwise i decide to add non Python related content  i will make sure to filter the feed.

**Comment by tseaver** [comment]
@techiediaries How is the new feed going to be different than https://www.techiediaries.com/tag/django/index.xml, which we already aggregate?

**Comment by techiediaries** [comment]
It doesn't work, no posts are fetched and I submitted it twice with no
luck. Please, can you take time to check it? Also the two blogs will
contain different posts so if it Ok can you please add it?

**Comment by techiediaries** [comment]
It doesn't work, no posts are fetched and I submitted it twice with no luck. Please, can you take time to check it? Also the two blogs will contain different posts so if it's Ok can you please add it?
