### ISSUE TITLE
Query params in feed URL break links

### ISSUE THREAD

**Issue by wearpants** [python/planet#245]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**: Ubuntu 14.04  
**Browser**:  Chromium 59
**Platform**: desktop  

## Problem
Sidebar links to feeds do not render properly if there are query parameters `?some=thing` in the url

## Details
```
[http://www.petehunt.net/blog/?feed=rss2]
name = Pete Hunt

[https://wearpants.org/feeds/petecode.xml?tag=python]
name = Petecode

[http://www.peterbe.com/oc-Python/rss.xml]
name = Peter Bengtsson
```

Produces:

```
<li><a href="http://pedro.valelima.com" title="Underwater log feed for python">Pedro Lima</a>
</li>
<li><a href="" title="">Pete Hunt</a>
</li>
<li><a href="" title="">Petecode</a>
</li>
<li><a href="https://www.peterbe.com/rss.xml" title="Peterbe.com">Peter Bengtsson</a>
```

**Comment by tjguk** [comment]
This is one of those annoying bugs which I can't reproduce in my development setup. We've seen quite a few of these, nearly always related to https feeds. Unless anyone else can reproduce, I'll have to talk to the infrastructure team to see if we can get access to the live server directly.

**Comment by ewdurbin** [comment]
This appears to also be related to fetching TLS feeds. Confirmed that with TLS fix, the proper link is fetched and rendered.
