### ISSUE TITLE
Gustavo Narea latest post not showing up

### ISSUE THREAD

**Issue by tjguk** [python/planet#247]
[email to planet@]

My blog is part of Planet Python but my latest Python article didn't show up in the feed: https://gustavonarea.net/blog/posts/docker-dev-python/

I used the "Python" tag like I always do, and I can see the entry in my Python feed: https://gustavonarea.net/blog/tags/python/feed/

Can you please have a look at this? I think/hope the article would be very relevant to the Python community.

**Comment by tjguk** [comment]
I asked him to nudge the post just in case, but it makes no difference

**Comment by tjguk** [comment]
Once again, I can't reproduce in my dev rig. I'll speak to the admin team about getting access to the debug logs from the planet run.

**Comment by gnarea** [comment]
Thanks again, @tjguk.

Since it works locally for you, I wonder whether CloudFlare is blocking requests from Planet Python in production. I guess that'll show up in the logs.

I have the option to whitelist IP addresses, in case yours are static.

**Comment by ewdurbin** [comment]
Confirmed this was also a TLS issue when fetching feeds. It is resolved.
