### ISSUE TITLE
Please add TestAndCode.com/rss

### ISSUE THREAD

**Issue by okken** [python/planet#251]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Test and Code

**My Blog RSS or ATOM Python specific feed url**: http://testandcode.com/rss 
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using http://castfeedvalidator.com/?url=http://testandcode.com/rss and it is valid!

The validator at w3.org isn't up to date. My feed is a valid feed for modern standards of podcasting. It's being hosted by http://fireside.fm/, done by one of the best names in podcasting, Dan Benjamin. They have a faq at https://fireside.fm/faq that recommends validating with castfeedvalidator.com

2. [x] My feed is a **Python Specific** feed

All entries in the feed will be of interest to some Python developers.

3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.

The old name of the podcast was "Python Test Podcast", which was already up on planet.python because I was hosting it alongside the blog at pythontesting.net. I changed the name and moved it to testandcode.com, but the content is still the same. About half the content is Python specific, and half is software testing topics of interest to a wider audience, but still very interesting to Python devs.

4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.
