### ISSUE TITLE
Change to Feed Swisscom ICT

### ISSUE THREAD

**Issue by mcgfeller** [python/planet#261]
# EDIT FEED
------------------------------------------------------------------------------
Hi, I want to change my current feed url from http://ict.swisscom.ch/tag/python/feed to https://ict.swisscom.ch/feed/?post_type=cubetech_post&cubetech_keyword=Python

## I checked the following required validations:  (mark all 4 with [x])

1. [X] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for changing my feed on Python Planet! :+1:

And thanks a lot for running the Planet!

Martin Gfeller, Swisscom

**Comment by tseaver** [comment]
@mcgfeller Sorry for the delay.  I went to check the new URL, and it looks empty (as does the old one).  Is there a problem with the site?

**Comment by mcgfeller** [comment]
@tseaver No problem. The new URL is empty because my first Python-related post in the new format will appear on Dec, 14th.  The old one is empty because our blog runners unfortuntely zapped the old setup. 

Best regards, Martin

**Comment by mcgfeller** [comment]
Hi Tres, I've updated an old post of mine to include the Python keyword, and indeed it shows it in the new URL. So all is fine. I remove the keyword again, so Planet users won't get my old post again. 

Thanks again and kind regards, Martin
