### ISSUE TITLE
Please add my Blog Feed

### ISSUE THREAD

**Issue by The-Judge** [python/planet#263]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Marc Richter's personal site  

**My Blog RSS or ATOM Python specific feed url**: https://www.marc-richter.info/category/python/planet-python-articles/feed/  
 
## I checked the following required validations:

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://www.marc-richter.info/category/python/planet-python-articles/feed/ and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
@The-Judge The feed is empty, AFAICT:  is that what you intend?

**Comment by The-Judge** [comment]
Hi @tseaver,
yes, there is no article assigned, yet, that's true and intended.

**Comment by tseaver** [comment]
Please reopen the issue when you have published an item to the feed / category.
