### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by shivonkar** [python/planet#271]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Shiv 

## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
@shivonkar You need to give us the URL of your Atom / RSS 2.0 feed.

**Comment by shivonkar** [comment]
HI,
I want to subscribe the posts with my email ID. How to do that

Thank you
Shiv

**Comment by tjguk** [comment]
I'm not sure what you're asking. If you want to subscribe *to* the posts, you need an RSS reader. There are services which will consume RSS feeds on your behalf and email you, but I don't know if that's what you need.

Could you ask the question a different way, please?

**Comment by shivonkar** [comment]
Hi,
Sorry for not being clear.

Please advise how can I get RSS reader to read posts and send email to me

Thank you
Shiv

**Comment by tjguk** [comment]
At the risk of sounding obvious: just use your favourite search engine and look for, eg "rss to email".

What you're asking for isn't a function of the Planet Python software; just look around for someone offering that service for any RSS feed. The RSS feed for Planet Python itself is: http://planetpython.org/rss20.xml

I hope that helps answer your question
