### ISSUE TITLE
Can we include the new Free Python job board as a feed in Planet Python?

### ISSUE THREAD

**Issue by salimfadhley** [python/planet#28]
Hi PP team. I've created a new, free Python job board. It's run according to open-source principles. Everything is free and to submit a new job you make a github pull request. It would be amazingly amazing if we could get this site's feed into Planet Python.

The feed is:
http://pythonjobs.github.io/atom.xml

The home page is:
http://pythonjobs.github.io

The title of the site is:
The Free Python Job Board

**Comment by tseaver** [comment]
Job postings seem off-topic to me for the Planet.  @voidspace, can you comment?

**Comment by salimfadhley** [comment]
Perhaps you are right - it's not really news. 

Is there some way we could get it linked from PP but not actually in the feed.

**Comment by tjguk** [comment]
That was my initial thought too (ie off-topic). But, on consideration, 
I'm not sure it's really a problem. It's definitely Python-related and I 
don't think I'd find it too jarring to have a job ad pop up in my Planet 
feed.

(I'd prevoiusly considered proposing technical feeds such as PyPI or a 
feed from the hg commits, which made me realise that I wasn't averse to 
non-blog feeds as such).

Personally I'd be +0, maybe even +0.5.

TJG

**Comment by salimfadhley** [comment]
Thanks Tim. I wouldn't want it to become annoying.

What we really want is to get this new thing live in place of the old,
year-defunct python.org job board.

The place where I worked used to rely on this to find good people. We
crafted the new board to be a perfect replacement.

**Comment by malemburg** [comment]
On 15.03.2015 10:23, Salim Fadhley wrote:
> Thanks Tim. I wouldn't want it to become annoying.
> 
> What we really want is to get this new thing live in place of the old,
> year-defunct python.org job board.
> 
> The place where I worked used to rely on this to find good people. We
> crafted the new board to be a perfect replacement.

FYI: The python.org job board is scheduled to go live again next week.

I don't think it's a good idea to post job ads through the planet.
Not so much because it's off-topic, but mostly because once we start
this, every single Python job board on the planet will want to
get added to the feed as well. And there are lots of those.

It may be more useful to add a separate planet instance
just for job ads.

-- 
Marc-Andre Lemburg
Director
Python Software Foundation
http://www.python.org/psf/

**Comment by holdenweb** [comment]
On Mar 15, 2015, at 11:46 AM, Marc-Andre Lemburg <notifications@github.com> wrote:

> On 15.03.2015 10:23, Salim Fadhley wrote:
> > Thanks Tim. I wouldn't want it to become annoying.
> > 
> > What we really want is to get this new thing live in place of the old,
> > year-defunct python.org job board.
> > 
> > The place where I worked used to rely on this to find good people. We
> > crafted the new board to be a perfect replacement.
> 
> FYI: The python.org job board is scheduled to go live again next week.
> 
HOORAY!!!!!!!!

> I don't think it's a good idea to post job ads through the planet.
> Not so much because it's off-topic, but mostly because once we start
> this, every single Python job board on the planet will want to
> get added to the feed as well. And there are lots of those.
> 
Agreed, it's off-topic for the technical channel the planet aims to be.

> It may be more useful to add a separate planet instance
> just for job ads.
> 
That's a useful adjunct idea if anyone can be bothered.

S

> -- 
> Marc-Andre Lemburg
> Director
> Python Software Foundation
> http://www.python.org/psf/
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Steve Holden steve@holdenweb.com / +1 571 484 6266 / +44 113 320 2335 / @holdenweb

**Comment by salimfadhley** [comment]
Fair enough, at the time I wrote the request I was unaware that the "Oficial" board was about to relaunch. I'm going to close this now.
