### ISSUE TITLE
Add feed

### ISSUE THREAD

**Issue by gramster** [python/planet#282]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Graham Wheeler  

**My Blog RSS or ATOM Python specific feed url**: http://www.grahamwheeler.com/categories/python.xml  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=http://www.grahamwheeler.com/categories/python.xml and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.

**Comment by gramster** [comment]
Thanks Tres. The link in the sidebar is the base URL without the "/categories/python.xml" suffix; was that intentional?

**Comment by tseaver** [comment]
When I look at the W3 validator output, the one warning is, "Self reference doesn't match document location."  The `<atom:link ref="self">` URL *does* match, but this one doesn't: `<link>https://www.grahamwheeler.com/</link>`. Maybe the Planet software may be using that link to build the sidebar.

**Comment by tseaver** [comment]
@gramster I updated the feed URL just now.
