### ISSUE TITLE
requesting to be added at planet python

### ISSUE THREAD

**Issue by backupchecker** [python/planet#30]
Hi,

I'm Carl Chenet, independent sysadmin, official Debian developer. I've been using Python for years and also contributed with small patches to the Python standard libraries, I use Python a lot for my personal projects and I think my blog could be interesting for the Python community. Here is the category dedicated to planet python :

http://carlchenet.com/category/planetpython/

Regards,
Carl Chenet

**Comment by tjguk** [comment]
Carl,

We need an RSS/Atom feed. Can I assume that this is the correct one to use?

http://carlchenet.com/category/planetpython/feed/

TJG

**Comment by backupchecker** [comment]
Thanks for the quick answer. Yes it is.

Regards,
Carl Chenet

**Comment by tjguk** [comment]
Added. Should start to appear after a few hours

**Comment by backupchecker** [comment]
Thanks!
