### ISSUE TITLE
Add new feed

### ISSUE THREAD

**Issue by grdl** [python/planet#303]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: [Gridarrow](https://www.gridarrow.com/blog/) 

**My Blog RSS or ATOM Python specific feed url**: https://www.gridarrow.com/blog/index.xml  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.gridarrow.com%2Fblog%2Findex.xml and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
@grdl Can you confirm that the entire feed is Python-related?  Just from scanning the titles / summaries for the current articles, I'm not sure I see that it is.

**Comment by grdl** [comment]
@tseaver I confirm Gridarrow is Python-related. It's a tool for streaming data into Excel using Python scripts. Articles in the feed showcase different solutions and use-cases, and all of them contain example Python code.
