### ISSUE TITLE
Add ABlog blog

### ISSUE THREAD

**Issue by abakan** [python/planet#31]
Hi,
I am developing [ABlog](http://ablog.readthedocs.org/) that converts a Sphinx projects to blog with feeds. ABlog releases and manual pages are all blog posts. Could you add its blog to the planet? Feeds are here: http://ablog.readthedocs.org/blog/atom.xml
Thanks!
Ahmet

**Comment by tjguk** [comment]
Added

**Comment by abakan** [comment]
Hi Tim,
Thanks for adding ABlog. I haven't seen recent posts on the planet though. Is it because ablog feed URL is added to your fork of planet repo? Does it need to be merged to python/planet?
Thanks,
Ahmet

**Comment by tjguk** [comment]
(Laughs). Sorry -- you're quite right; I didn't realise I was against my 
own fork. If no-one else gets there first, I'll go and fix it.

Feel free to submit an actual PR and I or someone can just merge it 
straight.

**Comment by berkerpeksag** [comment]
Done in https://github.com/python/planet/commit/69b637237460fd4ce181164ab1816037abc90ab9 :)

**Comment by abakan** [comment]
Thanks guys! I see that posts appeared on the planet page, and it's driving visitors to the website!
