### ISSUE TITLE
New python blog - Zero-with-Dot

### ISSUE THREAD

**Issue by OlegZero13** [python/planet#312]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Zero-with-Dot  

**My Blog RSS or ATOM Python specific feed url**: https://zerowithdot.com/feed.xml  
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by matrixise** [comment]
Hi @OlegZero13,

Do you think you could create a PR?

Thank you.

**Comment by OlegZero13** [comment]
I tried, but I can't push the updated code. I get 403. I am not sure if doing things correctly.

**Comment by tseaver** [comment]
@OlegZero13 You need to fork the repository and push your changes to your fork, which will then allow you to construct a PR here.

**Comment by OlegZero13** [comment]
Thank you @tseaver !
I just did what you said.
