### ISSUE TITLE
Request to add ofosos.org 

### ISSUE THREAD

**Issue by ofosos** [python/planet#325]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Mark Meyer / ofosos.org

**My Blog RSS or ATOM Python specific feed url**:  https://ofosos.org/tag/python/rss/
 
## I checked the following required validations: (mark all 4 with [x])

1. [X] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by rochacbruno** [comment]
Done! https://github.com/python/planet/commit/fcd9ccc6549fa0eb44679f4af30e716eddb5e48b

Will be fetched soon in the next server update cycle.

Thanks and welcome to Python Planet.
