### ISSUE TITLE
Request to add developers.redhat.com

### ISSUE THREAD

**Issue by rctrh** [python/planet#326]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Red Hat Developers

**My Blog RSS or ATOM Python specific feed url**: https://developers.redhat.com/blog/category/python/feed/atom/  or https://developers.redhat.com/blog/category/python/feed/rss/
 
## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by rochacbruno** [comment]
Hi @rctrh I have added this feed one year ago look https://github.com/python/planet/commit/e434669714725dac2059b60b4784e3ac89dfaed5

**Comment by rochacbruno** [comment]
The problem is that there are 2 feeds

https://developers.redhat.com/blog/tag/python/feed/ - which is included
and
https://developers.redhat.com/blog/category/python/feed/atom/ - which is not

Shoudl we use Category or Tag filtering?

**Comment by rochacbruno** [comment]
@rctrh ok! I gonna change to category
