### ISSUE TITLE
Please add my PlanetPython feed

### ISSUE THREAD

**Issue by dailymorn** [python/planet#33]
Hi,

I'm Raymond Li ... a software engineer by day and a Linode junkie by night. I've been using Python for a number of years now to keep it up-and-running. I think the Python community might find the python-related posts interesting. 

I created a PlanetPython tag: http://rayli.net/blog/tag/planetpython/feed/

Ray

**Comment by berkerpeksag** [comment]
Hi Raymond,

The first entry in the feed is "Test-driven infrastructure for WordPress". Could you please config your feed to show Python related entries? :)

**Comment by dailymorn** [comment]
I was worried about that one, too. :) 

I considered including it because the implementation uses PyUnit. However, the title probably isn't a great fit, so it's removed from the feed now.

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (a few hours or so).
