### ISSUE TITLE
add reachtim.com blog please

### ISSUE THREAD

**Issue by tiarno** [python/planet#348]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name:**  Tim Arnold / reachtim

**My Blog ATOM Python specific feed url** : https://reachtim.com/feeds/python.atom.xml

## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

ALSO: when I ran the sort program, a few other lines were moved in config.ini, not just mine. It looks right but I wanted to let you know since I didn't expect that. Thanks!

**Comment by matrixise** [comment]
Hi @tiarno 

I am really sorry, but I can't confirm your RSS feed because I can't have an access to your web site.
https://reachtim.com is unreadable and I can't have an access to the feeds subdirectory.

Moreover, when I try to read your feed with some tools, I can't read it. Could you do the necessary? Thank you so much and thank you for your proposal.

**Comment by matrixise** [comment]
@tiarno 
About the content of your RSS feed, there was an issue with the configuration of my RSS reader.
I confirm your RSS feed.

**Comment by matrixise** [comment]
See #349
