### ISSUE TITLE
Please add Quansight Labs blog

### ISSUE THREAD

**Issue by rgommers** [python/planet#353]
# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet

**My Name/Blog Name**: Quansight Labs Blog

**My Blog RSS or ATOM Python specific feed url**: https://labs.quansight.org/rss.xml

> IMPORTANT!!! **we need contact information to notify in case of any changes** Please send an email to `planet@python.org` title: `PR {number} sent to planet` with your email address + a link for the PR you opened.
 
## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed: this is a group blog for a lab that works on PyData projects (see https://www.quansight.com/labs)
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by matrixise** [comment]
I have created a PR for your RSS feed, thank you for your contribution. Have a nice day,

Stéphane

**Comment by rgommers** [comment]
thank you!
