### ISSUE TITLE
ADD FEED: Nathan Piccini Data Science Dojo Blog

### ISSUE THREAD

**Issue by NPiccini** [python/planet#356]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: Nathan Piccini Data Science Dojo Blog (e.g John Doe Awesome Blog)  

**My Blog RSS or ATOM Python specific feed url**: https://blog.datasciencedojo.com/tag/python-programming/rss/

## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by matrixise** [comment]
I close this issue. Thank you
