### ISSUE TITLE
Adding CodeGrades?

### ISSUE THREAD

**Issue by tjguk** [python/planet#358]
Hello there. Although I've backed away from Planet maintenance a while ago I suspect I still have push privs.

But before I go ahead and add something, can I ask the current maintainers whether you're happy for me to add the blog for CodeGrades? 

https://blog.codegrades.com/

It's a code learning scheme, currently launching with Python. (It's an initiative by Nicholas Tollervey who's done a lot around using Python in education etc.)

I know that there have been misgivings in the past about blogs which are only tangentially about Python, and I don't want to tread on any toes. I'll prep up a PR but I won't push it until I hear feedback on this.

**Comment by tjguk** [comment]
I've obviously been away from this job for too long: I've now asked the maintainer if he can provide a Python-specific feed -- which should presumably satisfy the Planet requirements?

**Comment by holdenweb** [comment]
Can't see why it wouldn't. Pretty much all of Nick Tollervy's output is
Python related, but if we have to filter out tubas and other music I guess
that's OK.

Kind regards,
Steve Holden

**Comment by tjguk** [comment]
Thanks, @holdenweb. A while ago, I'd just have pushed it in, but I've been out of the loop for a while and I wanted at least a 2nd opinion in case there had been any sensitivities about not-100%-Python feeds while I'd been away.

**Comment by matrixise** [comment]
Because the branch has been merged, I'm closing this issue

**Comment by tjguk** [comment]
Thanks, @matrixise
