### ISSUE TITLE
Adding another Python channel to Planet Python

### ISSUE THREAD

**Issue by reuven** [python/planet#36]
My DailyTechVideo.com site features a daily conference video. Many have to do with Python. I believe that the Python tag will be an appropriate addition to Planet Python.  It's at http://DailyTechVideo.com/.  Thanks!

**Comment by tseaver** [comment]
Can you please provide the URL for the Atom / RSS 2.0 feed for the Python tag?

**Comment by reuven** [comment]
Sorry about that: http://dailytechvideo.com/category/python/feed/
