### ISSUE TITLE
Continuum Analytics blog has been spammed

### ISSUE THREAD

**Issue by smontanaro** [python/planet#362]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**:  Win10
**Browser**:  Chrome
**Platform**: desktop

## Problem
It seems the Continuum Analytics blog has been spammed.

## Details
Here's a recent entry I arrived at by clicking a Planet Python link in my RSS reader:

https://www.anaconda.com/12-34-36810-coque-aimantee-iphone-x-hlsytk/

This would seem to be French spam trying to get me to buy an iPhone. Sorry can't be sure, it's been decades since high school and college French. I am fairly certain it's not Python-related. My RSS reader indicates that a dozen similar spams landed a couple hours ago.

**Comment by tseaver** [comment]
Thanks for the report, and apologies for the delay in responding.  I can't see any such articles now in the Anaconda feed:  please reopen if you see them again.
