### ISSUE TITLE
Add blog https://kenpythonic.blogspot.com

### ISSUE THREAD

**Issue by kenparkerjr** [python/planet#365]
# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet 

**My Name/Blog Name**:  Ken Pythonic 

**My Blog RSS or ATOM Python specific feed url**: https://kenpythonic.blogspot.com

1. [ x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x ] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [ x] My feed contains only content in English language.

**Comment by tseaver** [comment]
@kenparkerjr Can you please provide the URL of the RSS 2.0 / Atom 1.0 feed, rather than the blog homepage?  Please check it by pasting into the validator link above.

**Comment by tseaver** [comment]
Please reopen with an actual feed URL.
