### ISSUE TITLE
Request to add pythoncircle.com feed to python planet

### ISSUE THREAD

**Issue by anuragrana** [python/planet#366]
Hi, I want to add my feed to the Python Planet

**My Name/Blog Name**: PythonCircle
**My Blog RSS or ATOM Python specific feed url**: https://www.pythoncircle.com/feed/

> IMPORTANT!!! **we need contact information to notify in case of any changes** Please send an email to `planet@python.org` title: `PR {number} sent to planet` with your email address + a link for the PR you opened.
 
## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https%3A//www.pythoncircle.com/feed/ and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
As of this writing, the feed URL you provided returns an empty XML document.  Please provide a URL which actually contains Python-specific content.

**Comment by anuragrana** [comment]
Hi,
URL is returning valid XML. Please check screenshot here. https://a.uguu.se/CpP5s4Cx8zZG.jpg
Also the content is valid according to validator.w3.org.

**Comment by tseaver** [comment]
@anuragrana Apologies, I was fooled by line wrapping in gvim.

**Comment by anuragrana** [comment]
Thanks
