### ISSUE TITLE
Request to add techbeamers.com feed to python planet

### ISSUE THREAD

**Issue by techbeamers** [python/planet#368]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: techbeamers python

**My Blog RSS or ATOM Python specific feed url**: https://www.techbeamers.com/python-programming-tutorials/feed/

> IMPORTANT!!! **we need contact information to notify in case of any changes** Please send an email to `planet@python.org` title: `PR {number} sent to planet` with your email address + a link for the PR you opened.
 
## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Please submit the actual Atom / RSS 2.0 feed URL, rather than the HTML homepage for your feed.

**Comment by techbeamers** [comment]
Hi @tseaver - Yes, it was missed. I've now updated the feed URL as required and also tested it with the validator. Please check and thanks for mentioning it.
