### ISSUE TITLE
Samuel Sutch Amazon Spam

### ISSUE THREAD

**Issue by fragfutter** [python/planet#378]
Hi, I want to notify you of a bug/problem that is happening on the Planet.

## Problem
The feed of samuel sutch spams amazon affiliate book links with no further comment.

**Comment by pamoroso** [comment]
Now there is also Chinese spam but I don't know if it's related as the feed's owner name is not in English. See issue #379

**Comment by tseaver** [comment]
Thanks for the report. Samuel Sutch feed removed via 46bdda171e05fdcd7472c90c32a7a6f1cceb2175.
