### ISSUE TITLE
Chinese spam

### ISSUE THREAD

**Issue by pamoroso** [python/planet#379]
There are Chinese spam posts in the Planet Python feed, I'm not sure if it's related to issue #378:

- https://www.pyarab.com/ek/5.html
- https://www.pyarab.com/ek/4.html
- https://www.pyarab.com/ek/3.html
- https://www.pyarab.com/ek/2.html
- https://www.pyarab.com/ek/1.html

**Comment by pamoroso** [comment]
More Chinese spam went through Planet Python.

**Comment by jbradberry** [comment]
If you look at the main pyarab.com site itself, it looks like it has become a domain parking site, in Chinese.

**Comment by rochacbruno** [comment]
Removal PR merged, we will try to contact the author, if not possible then we just keep it out.

**Comment by tseaver** [comment]
Via #380.
