### ISSUE TITLE
Request to add PyCon Sweden blog to the feed

### ISSUE THREAD

**Issue by haard** [python/planet#38]
PyCon Sweden has created a blog at http://pyconse.tumblr.com/ which we'd like added to Planet Python

**Comment by berkerpeksag** [comment]
Thanks!

**Comment by The-Compiler** [comment]
Looking at [what's posted there now](http://pyconse.tumblr.com/) this doesn't seem Python-related at all - what happened?

**Comment by tseaver** [comment]
We should be backing that feed out until it is straigtend out.

**Comment by tseaver** [comment]
12315522cd37c36a8e9110723d89a6e4dd72c7f2 comments out the feed.  Please feel free to ask for it to be re-added when control is recovered.

**Comment by rochacbruno** [comment]
sort-ini command removed the commented lines, so I am pasting contents here for future.

```
# See: https://github.com/python/planet/issues/38#issuecomment-242277755		
[http://pyconse.tumblr.com/rss]		
name = PyCon Sweden
```

**Comment by matrixise** [comment]
@rochacbruno Do you agree if we close this issue (~ 3 years...)
