### ISSUE TITLE
Add https://www.stechies.com/python/

### ISSUE THREAD

**Issue by vaibhav94gupta** [python/planet#388]
Hi, I want to add my feed to the Python Planet 

My Name/Blog Name: Stechies

My Blog RSS or ATOM Python-specific url is: https://www.stechies.com/python/
 
1. [ ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [ ] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ ] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [ ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [ ] My feed contains only content in the English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
PR #399 will add the feed, once it validates.
