### ISSUE TITLE
Please add my Podcast to Planet Python

### ISSUE THREAD

**Issue by mikeckennedy** [python/planet#40]
Here's the website:
http://www.talkpythontome.com/

RSS feed:
http://www.talkpythontome.com/episodes/rss

iTunes:
https://itunes.apple.com/us/podcast/talk-python-to-me-python-conversations/id979020229

Description:
Talk Python to Me is a weekly podcast hosted by Michael Kennedy. The show covers a wide array of Python topics as well as many related topics (e.g. MongoDB, AngularJS, DevOps). The format is a casual 30-45 minute conversation with industry experts. 

Episodes:
http://www.talkpythontome.com/episodes/all

Let me know if this is the right data or you need something else!

Thanks,
Michael

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (a few hours at most).

**Comment by mikeckennedy** [comment]
Wonderful, thank you.
