### ISSUE TITLE
Please remove feed source

### ISSUE THREAD

**Issue by The-Judge** [python/planet#401]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
% not relevant %

## Problem
Roberto Alsina is publishing on his blog https://ralsina.me/ some content that is in Spanish, which is not in line with planetpython.org's required validation "_My feed contains only content in English language._". Last 8 posts he published were not in English.
Please remove the source.

## Details
![Unbenanntes Bild](https://user-images.githubusercontent.com/904987/76004670-2a2b1680-5f0a-11ea-98b6-9f68f331cb29.png)
![Unbenanntes Bild2](https://user-images.githubusercontent.com/904987/76004678-2d260700-5f0a-11ea-8fb6-6bd7532897c1.png)

Thanks.

**Comment by The-Judge** [comment]
2 more in the meantime...

**Comment by The-Judge** [comment]
More Spanish content hit the "strictly english, only" planet...

**Comment by rochacbruno** [comment]
I have raised the PR #402 I will merge it
