### ISSUE TITLE
Add Feed https://mobilunity.com/blog/hire-python-developers/

### ISSUE THREAD

**Issue by Mobilunity-Com** [python/planet#403]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**:  Mobilunity

**My Blog RSS or ATOM Python specific feed url**: https://mobilunity.com/blog/hire-python-developers/
 
## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://mobilunity.com/blog/hire-python-developers/ and it is valid!

2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
The URL you have provided is not an RSS or Atom feed.  Please reopen with the correct URL, if the site actually has such a feed.
