### ISSUE TITLE
Posts from my blog not showing up

### ISSUE THREAD

**Issue by cool-RR** [python/planet#418]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

I am using:  
**O.S**:   Windows 7
**Browser**:  Chrome
**Platform**: Desktop

Posts from my blog aren't showing up: https://blog.ram.rachum.com/

They used to show up regularly. Any idea why they're not?

**Comment by cool-RR** [comment]
Is anybody out there?

**Comment by tseaver** [comment]
The URL for your feed appears to be http://feeds.feedburner.com/RamRachumsBlog/planetpython, and has been so since #41 was merged five years ago.

**Comment by cool-RR** [comment]
@tseaver Okay, and is there something wrong with that URL? I'm trying to understand what you're saying here.

**Comment by tseaver** [comment]
@cool-RR That URL is not (as of today) a valid Atom / RSS 2.0 feed:  it is a `text/html` page.  I can't see a link on that page to an actual feed.
