### ISSUE TITLE
Update feed for Nick Efford

### ISSUE THREAD

**Issue by python33r** [python/planet#42]
Hey there!

Please could you change the old feed for Nick Efford (http://pythoneering.blogspot.co.uk/search/label/python) so that it points to my new blog?

Posts tagged `python` are at http://blog.efford.org/tag/python.html

The corresponding Atom feed is http://blog.efford.org/tag/feeds/python.atom.xml

**Comment by berkerpeksag** [comment]
Done, thanks!
