### ISSUE TITLE
Please add our podcast Podcast.__init__ to Planet Python

### ISSUE THREAD

**Issue by feoh** [python/planet#43]
Kind of funny that we all started two Python podcasts right around the same time :)

Please add ours to Planet Python

Website: http://www.podcastinit.com/
Blog RSS: http://podcastinit.com/feeds/all.atom.xml
Episode RSS Feed: http://podcastinit.podbean.com/feed/
iTunes: https://itunes.apple.com/us/podcast/podcast.-init/id981834425?mt=2&at=&ct=&ign-mpt=uo%3D6

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (a few hours at most).
