### ISSUE TITLE
Adding my python blogs to planet python

### ISSUE THREAD

**Issue by bhakunikaran** [python/planet#434]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**:  [Python Pool](https://www.pythonpool.com/)

**My Blog RSS or ATOM Python specific feed url**: https://www.pythonpool.com/feed/
 
## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in the English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

Thanks.

**Comment by matrixise** [comment]
Hi,

Because your feed is not a valid RSS or ATOM feed, I am going to remove it from the planet.

If you want to add your feed, please submit a PR with a valid RSS feed. Thank you
