### ISSUE TITLE
Python Morsels

### ISSUE THREAD

**Issue by jbradberry** [python/planet#438]
I've noticed the last several days that the same article from Python Morsels is at the top of the feed.  It looks like their feed is calculating a new timestamp every time it gets pulled.

**Comment by treyhunner** [comment]
Python Morsels maintainer here.

@jbradberry we had a bug that resulted in an article being published a week early but with the timestamp of a week later (a `filter(published_on__lte=now())` in our Django query had been removed by accident). 😓

The issue should be fixed now. Sorry for accidentally hogging the top of the feed for a week!

**Comment by jbradberry** [comment]
Yep, looks ok to me now.  :+1:
