### ISSUE TITLE
Please add my feed

### ISSUE THREAD

**Issue by jbencook** [python/planet#450]
# ADD FEED
-------------------------------------------------------------------------------

Hi, my name is Ben Cook and I want to add my feed to the Python Planet

**My Name**: Ben Cook

**My Blog RSS**: https://jbencook.com/feed.xml
 
## I checked the following required validations:

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://jbencook.com/feed.xml and it is valid!
2. [x] My feed is a **Python Specific** feed
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by tseaver** [comment]
Done in #451.
