### ISSUE TITLE
Request to add my blog

### ISSUE THREAD

**Issue by csparpa** [python/planet#48]
[This is my blog's URL](http://csparpa.github.io/blog) and [this is the related atom feed's URL](http://csparpa.github.io/blog/feeds/all.atom.xml). Thank you very much!

**Comment by berkerpeksag** [comment]
Hi Claudio,

Do you have a RSS feed only for Python posts?

Thanks!

**Comment by csparpa** [comment]
Yes... Do you need me to setup something else?

Claudio Sparpaglione
http://csparpa.github.io

**Comment by berkerpeksag** [comment]
Sharing the URL for python only posts would be enough, thanks. I can add http://csparpa.github.io/blog/feeds/all.atom.xml too, but if possible, narrowing the scope of the feed would be awesome :)

**Comment by csparpa** [comment]
Mmmm... I need to modify my feeds generation system (currently using Pelican). For the moment, please just add the link I gave you: I'll try to narrow down the feeds contents as soon as I can

Thank you so much!

**Comment by rochacbruno** [comment]
I guess pelican automatically creates a feed by category

http://csparpa.github.io/blog/feeds/python.atom.xml

**Comment by csparpa** [comment]
Yes you're right, that's the one that needs to be added :)
cheers!
