### ISSUE TITLE
Chris Moffitt link is pointing to the wrong place

### ISSUE THREAD

**Issue by chris1610** [python/planet#50]
For some reason, a couple of days ago, the link to my blog was replaced by another.

Chris Moffitt should point to http://pbpython.com

Right now it is pointing to http://d-salazar.com/

**Comment by tseaver** [comment]
The config [looks correct to me](https://github.com/python/planet/blob/fa016ba2d4259f3c5e0a215515f4f573f782ccdd/config/config.ini#L1202).  The Atom feed is referring to itself as 'd-salazar.com', which the planet is honoring.  If you fix the template, the planet will follow suit.

**Comment by chris1610** [comment]
Ok. Apparently something got borked on my site. I've updated it. Thanks for looking into it.
