### ISSUE TITLE
Remove feeds that degrade the planetpython experience

### ISSUE THREAD

**Issue by texasbrok** [python/planet#502]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**:  MacOs  11.6.1
**Browser**:  Chrome 97.0.4692.71
**Platform**: desktop

## Problem
(1) Certain blogs haven't thought about their audience and thus add noise rather than signal
(2) Planet doesn't validate that blogs apply standardized formatting to their code listings

Collectively, these problems degrade the experience of using planetpython.org, for beginning and experienced Python users alike.  Beginners will be misled about good practices, and old-timers will be frustrated to see low quality feeds clutter up the reading experience.

## Details
Regarding problem (1), there are two blogs that regularly publish poor quality articles:
- pythonforbeginners.com
- itsmycode.com

As an example, https://www.pythonforbeginners.com/lists/linked-list-in-python should never have seen the light of day.   Who is the audience for this article?  It seems to assume the audience has no Computer Science background whatsoever on the fundamental concept of linked lists, yet it jumps in with an object-oriented implementation, itself a fairly advanced concept.  And it wholly ignores the fact that PYTHON HAS AN IN-BUILT LIST CLASS that beginners should simply use out of the box rather than try to recreate.  This article causes more confusion than clarity, especially for beginners that won't know to ignore it.  

This one article is part of a larger trend for pythonforbegginers.com.  Many of its articles suffer from this same problem of poor conceptualization of the reader and thus poor quality.  Furthermore, they embed so many ads, the articles are really fragmented and lacking in continuity as one reads.  The itsmycode.com blog is slightly better in terms of embedded ads, but many of their articles are gratuitously verbose explanations of trivial concepts explained much more concisely and clearly in Python's own docs (e.g. NOBODY needs an entire article on str.isdigit()).

I bear the authors no ill will, but from my vantage point their aim is to drive ad revenue more than to carve out a niche audience and to really provide high quality content for it.  Please, please remove both these blogs.  Doing so will immediately improve the experience of those browsing planetpython.org.

Regarding problem (2), could you add to the Planet input process a sixth validation from blog authors that they apply standard formatting (like pep8, flake8, or black) to their code listings?  It's far too common for some blogs to publish code that does not conform to best formatting practices (and the two mentioned above are prime examples).

Thanks.

**Comment by texasbrok** [comment]
Here's another article that purports to help Python beginners but actually misleads them with terrible techniques:
https://www.pythonforbeginners.com/basics/lambda-function-in-python

Nothing there is a language violation, but the recommendations and code examples are horribly non-Pythonic.  Again, beginners won't know that they should run far away from this blog.  Hosting it on Planet is merely frustrating for those that know better, but worse, it could lead unsuspecting beginners down a path that will harm their learning.

**Comment by keto** [comment]
https://itsmycode.com/solved-attributeerror-nonetype-object-has-no-attribute-get/
https://itsmycode.com/solved-attributeerror-float-object-has-no-attribute-get/
https://itsmycode.com/solved-attributeerror-list-object-has-no-attribute-get/
https://itsmycode.com/solved-attributeerror-int-object-has-no-attribute-get/
https://itsmycode.com/solved-attributeerror-str-object-has-no-attribute-get/

Exactly the same article, just the data type changed. I would consider this as spam.

**Comment by malemburg** [comment]
Planet Python is meant as news aggregator. As such, it does not apply restrictions on the content, other than requiring a Python focus.

Removing SEO spam as you can find with recent "It's My Code" postings is fine, though, and so #521 was merged.

**Comment by wylee** [comment]
Re Python for Beginners, if you look at their most recent post about inserting into a sorted list, I think it's pretty obviously spam. The post contains no real useful info for beginners (IMO it's actively harmful content for beginners, as are all the posts I've seen) and the site is very spammy in general. IMO, removal of this site should be reconsidered.
