### ISSUE TITLE
Adding Pyarmy 

### ISSUE THREAD

**Issue by pawangeek** [python/planet#503]
Hi, I want to add my feed to the Python Planet

**My Name/Blog Name**: Pyarmy

**My Blog RSS or ATOM Python-specific feed url**: [Feed URL](http://validator.w3.org/check.cgi?url=https%3A//pyarmy.com/tag/python/rss/)

## I checked the following required validations:

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by matrixise** [comment]
Hi, when I check your domain (pyarmy.com), this one is used by GoDaddy

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/38737/183940202-a8fe4f36-5000-4564-a053-6a16b3d1e719.png">
