### ISSUE TITLE
ADD feed https://cmlzagk.github.io/feeds/python.atom.xml

### ISSUE THREAD

**Issue by cmlzaGk** [python/planet#504]
# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet 

**My Name/Blog Name**: Rishi Maker / cmlzaGk
**My Blog RSS or ATOM Python specific feed url**:  https://cmlzagk.github.io/feeds/python.atom.xml

## I checked the following required validations: (mark all 5 with [x])

1. [X ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [ X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X ] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [X ] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

> NOTE: If you are adding a podcast feed please validate using http://castfeedvalidator.com/

**Comment by cmlzaGk** [comment]
Any updates

**Comment by matrixise** [comment]
I have created a PR for your RSS feed and this one has been merged into the main branch.

Have a nice day and sorry for the delay.
