### ISSUE TITLE
Add Paolo Amoroso's Journal

### ISSUE THREAD

**Issue by pamoroso** [python/planet#510]
# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet as per PR #508

**My Blog Name**: Paolo Amoroso's Journal

**My Blog RSS or ATOM Python specific feed url**: https://journal.paoloamoroso.com/tag:Python/feed/

## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://journal.paoloamoroso.com/tag:Python/feed/ and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Note**: This is my second submission to Planet Python, which already includes my other blog named *Paolo Amoroso*.

**Comment by matrixise** [comment]
Thanks to @malemburg for his help with your RSS feed. I can close this issue. Thank you and sorry for the big delay in my reply :-(
