### ISSUE TITLE
Request to add feed

### ISSUE THREAD

**Issue by Chris7** [python/planet#52]
I'm not sure what the bar is for how established your page is, but I've started writing up on my python related experiences using python for bioinformatics and other tool developments.

It is located here:
rss feed: http://pyinformatics.blogspot.com/feeds/posts/default?alt=rss
atom feed: http://pyinformatics.blogspot.com/feeds/posts/default

I'd love to be a part of Planet Python.

Thank you,
Chris Mitchell

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (an hour or two, normally).
