### ISSUE TITLE
Remove ItsMyCode for spamming

### ISSUE THREAD

**Issue by The-Judge** [python/planet#521]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet. 

## Problem
ItsMyCode (https://itsmycode.com/) is currently spamming eaqual articles, which are all the same, with only one exception: They name another, popular Python Module. The rest of all the articles is the same and sums to "If you encounter a module not found error, install it." 

Examples:

* https://itsmycode.com/no-module-named-crypto/
* https://itsmycode.com/no-module-named-colorama/
* https://itsmycode.com/no-module-named-click/
* https://itsmycode.com/no-module-named-bs4/
* https://itsmycode.com/no-module-named-boto3/
* https://itsmycode.com/no-module-named-bio/
* https://itsmycode.com/no-module-named-absl/

All articles exchange more or less only the name of the module and thus flood the planet site.

Thanks.

**Comment by alexifm** [comment]
Thanks for this.  This blog needs to be taken off the roll.

**Comment by The-Judge** [comment]
And another 5 or 6 Spam articles published... What's so hard with this merge?

**Comment by alexifm** [comment]
@matrixise Could you merge the PR in?  Much appreciated.

**Comment by alicederyn** [comment]
This would be really great, the site is googlebait garbage.

**Comment by alicederyn** [comment]
I note this was also addressed by #514 in June which was also not merged.

**Comment by sandrotosi** [comment]
please, this, it's unbearable

**Comment by ross-g** [comment]
Came here for exactly the same reason, 22 garbage "articles" in just the past day alone.

**Comment by The-Judge** [comment]
Seems to be an extraordinary difficult merge. a.k.a "We don't care".

**Comment by sandrotosi** [comment]
there hasnt been any commits since March, so this seems to be more an issue of maintenance

**Comment by pamoroso** [comment]
Can anything be done please? Is Planet Python still maintained?

**Comment by The-Judge** [comment]
Seems like it isn't. Plus, it seems like it's working on killing it's reputation...

**Comment by The-Judge** [comment]
Planet Python staff - anything I can help with? Do you have a staff shortage? Can I sign up somehow to become a team member and get merge privileges?
I mean: 6 days+ to reviews a trivial config-merge request...?

**Comment by smontanaro** [comment]
@matrixise I see you've been recently active closing other issues. Can you help?

**Comment by sandrotosi** [comment]
i've asked in https://discuss.python.org/t/maintenance-of-planetpython-org/18026 if i can take over (or at least be part of the maintenance team of planet python)

**Comment by The-Judge** [comment]
@sandrotosi I did the same. But again: No reply really ... Did you hear anything?
I think it is unbelievable that not a single representative, neither from this project, nor the official Python forums replies to help offers for days. Does Python have issues?

**Comment by The-Judge** [comment]
@malemburg Thank you very much :)
