### ISSUE TITLE
Remove feed for efficientcoder.net (irrelevant)

### ISSUE THREAD

**Issue by tephyr** [python/planet#529]
# REPORT A PROBLEM
-------------------------------------------------------------------------------

I am using:  
**O.S**:  N/A
**Browser**:  N/A
**Platform**: (mobile, tablet, desktop)  N/A

## Problem
The feed from https://efficientcoder.net/ is **not** Python-specific, and has had very few Python articles in the last several years.  In addition, the site's About Me section is blank, indicating the author does not want to be contacted.

This site has several hallmarks of a spam site.  Regardless of whether it is or no, it should be removed from this Python-specific feed.

## Details
Author is listed on Planet Python as [Ahmed Bouchefra](https://efficientcoder.net/).

Thanks.

**Comment by malemburg** [comment]
Can you create a PR for this ? Thanks.

**Comment by malemburg** [comment]
I could not find an entry for the feed you listed in the config.ini file, so closing the request.
