### ISSUE TITLE
Drop Codementor due to low-quality and spam posts?

### ISSUE THREAD

**Issue by Kwpolska** [python/planet#534]
The Codementor feed in Planet Python has low quality and low value. It is not curated at all by anyone over at Codementor, so the posts that can end up in Planet Python are often lacking in content. Their RSS feeds often contain a single sentence that may or may not describe the content.

Here are the latest three posts from Codementor, currently on the Planet Python web page, complete with their content as seen in RSS readers (it’s so short it fits on one line):

* [Functional Programming explained...](https://www.codementor.io/nimeshneema/functional-programming-explained-21kv7pa8yt) — basics of functional programming
* [printf function in C programming Language](https://www.codementor.io/nimeshneema/printf-function-in-c-programming-language-21knq0xgbj) — In continuation of basics of C programming language series
* [#include explanation in Language C](https://www.codementor.io/nimeshneema/include-explanation-in-language-c-21jqzjxqrt) — another part in basics of language C

The posts have nothing to do with Python, but the author has added a Python tag, so they showed up on Planet Python. The posts are of very low quality and contain almost no useful content. For example, the last post starts with `Start writing here...n C programming, the #include directive is used to include the contents of a header file in a source code file.` — which makes it obvious the author did not even proof-read their post.

**Comment by matrixise** [comment]
Hello, I am going to check that.

**Comment by Kwpolska** [comment]
Thanks, this should improve the Planet’s quality.
