### ISSUE TITLE
Please add my book's blog feed

### ISSUE THREAD

**Issue by amitsaha** [python/planet#54]
Hello, please add my book "Doing Math with Python" (http://doingmathwithpython.github.io/ )'s blog feed to Python planet:

Feed: http://doingmathwithpython.github.io/feeds/all.atom.xml

Thank you.

**Comment by tjguk** [comment]
Thanks; added. Should appear in the next data refresh in a few hours

**Comment by amitsaha** [comment]
Thank you.
