### ISSUE TITLE
✨Add new blog: TypeThePipe

### ISSUE THREAD

**Issue by TypeThePipe** [python/planet#546]
!!! Please choose one template below ADD FEED, EDIT FEED or INFORM a BUG/PROBLEM.
PLEASE: Remove this headline and the unused templates!!!

# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet or I want to change my current feed url from https://typethepipe.com/categories/python/index.html

**My Name/Blog Name**: _TypeThePipe_  

**My Blog RSS or ATOM Python specific feed url**:  https://typethepipe.com/categories/python/index.html

## I checked the following required validations: (mark all 5 with [x])

1. [X] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [X] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by matrixise** [comment]
ok, this RSS feed has been added in the past (July 31st) and I have not closed this issue.

Sorry
