### ISSUE TITLE
Please add The Python Show Podcast

### ISSUE THREAD

**Issue by driscollis** [python/planet#551]
Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: The Python Show Podcast

**My Blog RSS or ATOM Python specific feed url**: https://pythonshow.com/feed

## I checked the following required validations: (mark all 5 with [x])

1. [x ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [ x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ ]x I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [ x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [ x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by matrixise** [comment]
Hi Mike,

There is no redirect between https://pythonshow.com (HTTP 404) and https://www.pythonshow.com, could you fix it?

Thank you

**Comment by driscollis** [comment]
I believe this is fixed now. Sorry for the delay

**Comment by malemburg** [comment]
I've added a PR for this (see #561).

**Comment by malemburg** [comment]
Merged the PR, since I did not hear back from @matrixise

**Comment by malemburg** [comment]
Note: I'm not sure whether anything needs to be done in order to have this change take effect.

**Comment by driscollis** [comment]
It didn't pick up anything for the first week or so, but it appears to be working now. Thanks so much!
