### ISSUE TITLE
Request reinstatement for http://pyright.blogspot.com/

### ISSUE THREAD

**Issue by infixum** [python/planet#567]
!!! Please choose one template below ADD FEED, EDIT FEED or INFORM a BUG/PROBLEM.
PLEASE: Remove this headline and the unused templates!!!

# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet or I want to change my current feed url from CURRENT_URL_HERE to NEW_URL_HERE

**pyright**: MY_NAME_OR_BLOG_NAME_HERE (e.g John Doe Awesome Blog)  

**[My Blog RSS or ATOM Python specific feed url](http://pyright.blogspot.com/)**: MY_FEED_URL

## I checked the following required validations: (mark all 5 with [x])

1. [ x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [ x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x ] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [ x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [ x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

> NOTE: If you are adding a podcast feed please validate using http://castfeedvalidator.com/

# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**:  
**Browser**:  
**Platform**: (mobile, tablet, desktop)  

## Problem
DESCRIBE_THE_PROBLEM_HERE

## Details
INCLUDE_OUTPUTS_OR_SCREENSHOTS_HERE

Thanks.

---------------------------------------------------------------------------------

!!! PLEASE remove the unused templates above !!!

**Comment by matrixise** [comment]
Hi, there,

Is it okay if you create a PR and then we merge it?

Have a nice day,

**Comment by infixum** [comment]
Hi, Stephane.

Sorry for the trouble.

The blog is showing up on the planet. I think I just missed my name in the
list. Apologies for the noise.

If I need to take action to close the ticket, please let me know (I'm not a
strong git user).

Thanks for all the work you do and again, apologies for the trouble.

Carl T.

**Comment by matrixise** [comment]
Hi Carl,

No problem, I close the issue. 

Have a nice day,

**Comment by infixum** [comment]
Thanks a ton, Stephane.
