### ISSUE TITLE
Planet Python SSL cert is expired

### ISSUE THREAD

**Issue by jkugler** [python/planet#571]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**:  Linux
**Browser**:  Chrome
**Platform**: (mobile, tablet, desktop)  Desktop

## Problem
The site's SSL certificate is expired.

## Details
Expired as of Wednesday, August 21, 2024 at 3:42:45 PM

Thanks.

**Comment by hugovk** [comment]
cc @JacobCoffee
