### ISSUE TITLE
Invalid RSS feed 

### ISSUE THREAD

**Issue by Mariatta** [python/planet#578]
These two feed seem invalid. What should we do?

## Python bytes

URL: https://www.castfeedvalidator.com/validate.php?url=https://pythonbytes.fm/episodes/rss

https://github.com/python/planet/blob/0dbf9ba09de40199a9edaff8ea748327f5eb471a/config/config.ini#L1110-L1111

![Screenshot 2024-10-08 at 4 13 57 PM](https://github.com/user-attachments/assets/998369dd-3af9-4c1f-a1f1-e43362ecc0f8)

![Screenshot 2024-10-08 at 3 56 48 PM](https://github.com/user-attachments/assets/5ca47929-ce12-42c1-b544-a01f8ad23c52)

## Talk Python to me

URL: https://www.castfeedvalidator.com/validate.php?url=http://www.talkpythontome.com/episodes/rss

https://github.com/python/planet/blob/0dbf9ba09de40199a9edaff8ea748327f5eb471a/config/config.ini#L1398-L1399

![Screenshot 2024-10-08 at 3 56 42 PM](https://github.com/user-attachments/assets/24fd9668-7628-4c5a-84ad-236a0cd25099)

![Screenshot 2024-10-08 at 4 12 57 PM](https://github.com/user-attachments/assets/d98cc9e9-9343-4838-8d62-8caccb2d4159)

**Comment by Mariatta** [comment]
@mikeckennedy  Can you please check your rss feed? Do you have new feed urls?

**Comment by mikeckennedy** [comment]
Hi @Mariatta Thanks. I did just check it and the mp3 file seems fine:

https://talkpython.fm/episodes/download/479/designing-effective-load-tests-for-your-python-app.mp3

Was that the issue or something else? I'll look at the other issues but I'm suspicious that it's not us if they say they can't get the mp3 downloaded and it is working OK. Unless it's a problem for others, then I'll check for sure.

**Comment by mikeckennedy** [comment]
Another example, it says "failed to load website" https://pythonbytes.fm/ but that works fine as far as I can tell.

**Comment by Mariatta** [comment]
Yeah I'm not sure why it was erroring out when I was trying earlier. Actually trying again, the validator for both are now working, so maybe the castvalidator site was the problem.

I do notice that now this is showing some redirect 
https://www.castfeedvalidator.com/validate.php?url=http://www.talkpythontome.com/episodes/rss

Seems like the updated url is now https://talkpython.fm/episodes/rss

Would you like to update the config.ini file with this new url?
https://github.com/python/planet/blob/0dbf9ba09de40199a9edaff8ea748327f5eb471a/config/config.ini#L1398-L1399

**Comment by mikeckennedy** [comment]
Hi, thanks. I'm not sure what the deal was. However, I did do some tidying up on the RSS feed and added a couple of recently defined tags.

I did validate them with this slightly nicer looking validator:

* https://podba.se/?url=https://talkpython.fm/episodes/rss
* https://podba.se/?url=https://pythonbytes.fm/episodes/rss

I'd love if you could update the RSS feeds to https://talkpython.fm/episodes/rss and https://pythonbytes.fm/episodes/rss

**Comment by mikeckennedy** [comment]
Thank you @Mariatta
