### ISSUE TITLE
Please add the Python category on my blog

### ISSUE THREAD

**Issue by DRMacIver** [python/planet#59]
Feed is http://www.drmaciver.com/category/python/feed/

It's mostly about [Hypothesis](http://hypothesis.readthedocs.org/en/latest/) development, but occasionally other things too.

(Adding my whole blog would probably be a bad idea. It has a lot of non python stuff on it)

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (an hour or two at most).

**Comment by DRMacIver** [comment]
Thanks!
