### ISSUE TITLE
Please add Podcast.__init__ - a Python Podcast

### ISSUE THREAD

**Issue by feoh** [python/planet#60]
We're at http://www.podcastinit.com and our feed is at http://podcastinit.podbean.com/feed/

Thank you!

-Chris, Co-host

**Comment by berkerpeksag** [comment]
Added. Great podcast, by the way :)

**Comment by feoh** [comment]
Thank you so much! Glad you're enjoying it. It's great fun to make.

On Tue, Jul 7, 2015 at 10:51 AM, Berker Peksag <notifications@github.com>
wrote:

> Added. Great podcast, by the way :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/planet/issues/60#issuecomment-119227179>.
>



-- 
Christopher Patti - Geek At Large | GTalk: cpatti@gmail.com | AIM:
chrisfeohpatti | P: (260) 54PATTI
"Technology challenges art, art inspires technology." - John Lasseter, Pixar
