### ISSUE TITLE
Call for papers announcement

### ISSUE THREAD

**Issue by afilina** [python/planet#67]
Hi,

Could you please add this announcement? We're looking for Python speakers. We added additional Python slots this year. I hope your community sends plenty of awesome speakers.
You can use this image if space allows: https://confoo.ca/images/content/confoo-master.jpg

<title>ConFoo 2016 is looking for Python speakers</title>

<p>ConFoo is once more seeking passionate speakers for the upcoming conference.</p>

<p>The event is happening in Montreal, Canada, between February 24th and 26th, 2016. It is an exciting conference for web developers with speakers from all over the world. It unites many web programming languages under one roof, as well as other topics related to web development. The <a href="https://confoo.ca/en/call-for-papers">call for papers</a> closes on September 20th.</p>

<p>For the last few years, ConFoo renewed 50% of its speakers. If you're new to this conference, you should definitely submit.</p>

<p>If you would just like to attend, there is a <a href="https://confoo.ca/en/register">discount</a> until October 13th.</p>

**Comment by tseaver** [comment]
@afilina Planet Python is a pure aggregator:  it has no content of its own.  Feel free to ask that one or more of the blogs aggregated here include your CFP.
