### ISSUE TITLE
Request to add feed

### ISSUE THREAD

**Issue by andreagrandi** [python/planet#68]
Hi,

this is my feed about Python https://www.andreagrandi.it/category/python/

If you find it useful, please feel free to include it in Planet Python, cheers.

**Comment by tjguk** [comment]
Added; thanks. Should appear at the next refresh, after a few hours

**Comment by andreagrandi** [comment]
@tjguk hi Tim! Thanks for the quick reply :)
By the way, I've just checked the link that appears on Planet Python for my name (search "Andrea Grandi" in the page): http://planetpython.org/ and it looks like it points to ```http://planetpython.org/``` instead of pointing to ```https://www.andreagrandi.it/category/python/```

**Comment by tjguk** [comment]
Not sure. That did used to happen with https://-based feeds, but I think
that was fixed a year ago, and I can see other feeds (eg ClusterHQ)
which are https:// and don't have the problem. I don't have the time to
dive in and debug now.

To see if it helps, I've changed your URL to http:// -- which then
redirects to https://.

Feel free to attempt to debug it yourself: you know where the code is!

**Comment by andreagrandi** [comment]
@tjguk I will try to ask on #python IRC channel
