### ISSUE TITLE
Request to add feed

### ISSUE THREAD

**Issue by jbradberry** [python/planet#69]
Please add my blog's Python feed to Planet Python.

    [http://jeffbradberry.com/feeds/python.atom.xml]
    name = Jeff Bradberry

**Comment by tseaver** [comment]
That URL 404's for me.

**Comment by jbradberry** [comment]
I have a draft article that I was waiting on this to publish, which will populate that feed.

**Comment by jbradberry** [comment]
It's published now.

**Comment by tseaver** [comment]
Your feed should show up in the next update cycle (an hour or two).
