### ISSUE TITLE
Request To Add Feed

### ISSUE THREAD

**Issue by rebeccasamuelson** [python/planet#82]
Can you add the Python posts from our blog? We teach and train data scientists and data engineers.

http://www.galvanize.com/blog/tag/python/

**Comment by tseaver** [comment]
Can you please post the URL of the actual Atom/RSS 2.0 feed itself?

**Comment by rebeccasamuelson** [comment]
Yes, here you go: http://www.galvanize.com/blog/tag/python/feed/

On Mon, Nov 9, 2015 at 6:46 AM, Tres Seaver <notifications@github.com>
wrote:

> Can you please post the URL of the actual Atom/RSS 2.0 feed itself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/planet/issues/82#issuecomment-155083283>.
>



-- 
Rebecca Samuelson
Technical Marketing Manager

111 S Jackson St | SEA, WA 98104
704.654.7371 Mobile
[image: Twitter] <https://twitter.com/galvanize>[image: Facebook]
<https://www.facebook.com/GalvanizeHQ>

**Comment by tseaver** [comment]
Thanks!  Your feed should appear in the next update cycle (an hour or two).

**Comment by rebeccasamuelson** [comment]
Thank you!!

On Mon, Nov 9, 2015 at 11:25 AM, Tres Seaver <notifications@github.com>
wrote:

> Thanks! Your feed should appear in the next update cycle (an hour or two).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/planet/issues/82#issuecomment-155165085>.
>



-- 
Rebecca Samuelson
Technical Marketing Manager

111 S Jackson St | SEA, WA 98104
704.654.7371 Mobile
[image: Twitter] <https://twitter.com/galvanize>[image: Facebook]
<https://www.facebook.com/GalvanizeHQ>
