### ISSUE TITLE
Tweet about a specific Python post not appearing in @planetpython Twitter stream ...

### ISSUE THREAD

**Issue by vasudevram** [python/planet#89]
... although the post itself did appear on Planet Python.

This is the post in question:

http://jugad2.blogspot.com/2015/11/convert-xlsx-to-pdf-with-python-and.html

It was posted on jugad2.blogspot.com on Monday, November 23, 2015.

Some hours later, it appeared on Planet Python, as is normal, since the post had the label python, and the subfeed jugad2.blogspot.com/search/label/python is included as a feed in Planet Python.

But the tweet about the post did not appear in the @planetpython Twitter stream, although it should have.

**Comment by tseaver** [comment]
@vasudevram The `@planetpython` Twitter account is not managed by the Planet Python team:  please contact the owner, (Marco Rodriges, `@goticx` on Twitter) to report this issue.

**Comment by vasudevram** [comment]
@tseaver  I first asked Michael Foord what to do about this issue, since he is the one who added my blog's Python subfeed to the Planet. He told me to raise an issue here. Now I will contact Marco as you suggest. Thanks.

**Comment by vasudevram** [comment]
@tseaver Just checked the @goticx Twitter account you referred to. It does not seem to belong to Marco. The name Maria Joes Castro is mentioned there as the person who is @goticx.

**Comment by tseaver** [comment]
My bad misspelling Marco's Twitter handle:  it should be `@gothicx`.

**Comment by vasudevram** [comment]
Ok, thanks.

**Comment by vasudevram** [comment]
Found that @gothicx is Marco's; but a protected account. Sent follow req.
so as to be able to DM him. No reply after a few days. Know any other way
to contact him, email etc.?


On Saturday, November 28, 2015, Tres Seaver <notifications@github.com>
wrote:

> My bad misspelling Marco's Twitter handle: it should be @gothicx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/planet/issues/89#issuecomment-160327650>.
>


-- 
Vasudev Ram - Dancing Bison Enterprises
Fellow at the Python Software Foundation
Independent software consultant and trainer
- Python, C, Linux, databases, open source
About: http://jugad2.blogspot.in/p/about-vasudev-ram.html
LinkedIn: http://www.linkedin.com/in/vasudevram
ActiveState Code recipes:
https://code.activestate.com/recipes/users/4173351

**Comment by lac22** [comment]
Is it this person?
https://github.com/gothicx?tab=activity
if so there is a gmail address there.

Laura


In a message of Thu, 03 Dec 2015 09:50:47 -0800, Vasudev Ram writes:

**Comment by vasudevram** [comment]
Yes, it must be him. Thanks a lot, Laura

CC'ing him.

Marco: Michael Foord -> Github issue -> Tres Seaver -> You, is the chain I
followed :-)

Coul you please look into this issue, if you are the right person for it?

It is about a missing @planetpython tweet - for a blog post by me that
appeared on the Planet site but not in the tweets. Details on the Planet's
Github issues page. Tweets did appear for all my previous Python posts [1].

Thanks,
Vasudev
---
[1] : jugad2.blogspot.com/search/label/python
---

On Thursday, December 3, 2015, lac22 <notifications@github.com> wrote:

> Is it this person?
> https://github.com/gothicx?tab=activity
> if so there is a gmail address there.
>
> Laura
>
>
> In a message of Thu, 03 Dec 2015 09:50:47 -0800, Vasudev Ram writes:
> >Found that @gothicx is Marco's; but a protected account. Sent follow req.
> >so as to be able to DM him. No reply after a few days. Know any other way
> >to contact him, email etc.?
> >
> >
> >On Saturday, November 28, 2015, Tres Seaver <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> >wrote:
> >
> >> My bad misspelling Marco's Twitter handle: it should be @gothicx.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/python/planet/issues/89#issuecomment-160327650>.
> >>
> >
> >
> >--
> >Vasudev Ram - Dancing Bison Enterprises
> >Fellow at the Python Software Foundation
> >Independent software consultant and trainer
> >- Python, C, Linux, databases, open source
> >About: http://jugad2.blogspot.in/p/about-vasudev-ram.html
> >LinkedIn: http://www.linkedin.com/in/vasudevram
> >ActiveState Code recipes:
> >https://code.activestate.com/recipes/users/4173351
> >
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >https://github.com/python/planet/issues/89#issuecomment-161730045
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/planet/issues/89#issuecomment-161739007>.
>


-- 
Vasudev Ram - Dancing Bison Enterprises
Fellow at the Python Software Foundation
Independent software consultant and trainer
- Python, C, Linux, databases, open source
About: http://jugad2.blogspot.in/p/about-vasudev-ram.html
LinkedIn: http://www.linkedin.com/in/vasudevram
ActiveState Code recipes:
https://code.activestate.com/recipes/users/4173351

**Comment by gothicx** [comment]
Hi Vasudev,

I don't control the tweets on planetpython, they come directed from the
plant python aggregator. I would like to give the control of this to
someone from planet python as I'm not really interested.

Kind regards,
--
Marco Rodrigues
http://lu.linkedin.com/in/gothicx

**Comment by tjguk** [comment]
Marco -- I'm happy to take over the Twitter account on behalf of the
Planet maintainers if you'd like. Email me offlist with the details
(mail@timgolden.me.uk).

But that doesn't get us any closer to understanding how the tweets are
generated as I don't *think* it's part of the Planet codebase.
Presumably someone somewhere has set up an RSS -> Twitter integration
service, but I don't know who / where.

TJG

**Comment by tjguk** [comment]
Vasudev,

I've just taken ownership of the Planet Twitter feed from Marco.

However, the RSS -> Twitter feed is simply via the twitterfeed
service[*], so the likelihood of our finding why a specific RSS entry
didn't tweet is pretty much nil unless we want to pursue it with
whatever support they offer.

TJG

[*] http://twitterfeed.com/

**Comment by vasudevram** [comment]
Hi Marco,

I understand. Thanks for the update.

Kind regards
Vasudev
---
Vasudev Ram - Dancing Bison Enterprises
http://jugad2.blogspot.in/p/about-vasudev-ram.html

**Comment by vasudevram** [comment]
Hi Tim,

Got it. I appreciate your checking this out and replying on this.

I just viewed TwitterFeed's own tweet stream (@twfeed); they mention recent
issues with their own system and also Twitter having some issues. I guess
this could be why that one tweet did not go through. It only happened for
that one post, a subsequent post of mine got tweeted, so I think the issue
is solved. I don't think we need to contact TwitterFeed support.

As an aside, TwitterFeed looks interesting and is from Bitly.

Thanks a lot.
Vasudev
---
http://jugad2.blogspot.in/p/about-vasudev-ram.html
