### ISSUE TITLE
Request addition of www.programandociencia.com

### ISSUE THREAD

**Issue by alexandrejaguar** [python/planet#90]
Hi everyone, this is Alex.
Could you please add www.programandociencia.com to Planet Python?
We post about Python on scientific subjects, every week.
Thank you very much.

**Comment by rochacbruno** [comment]
Hi alexandre, can you send a specific link to your Python only feed?

**Comment by alexandrejaguar** [comment]
Hey Bruno,
it's http://www.programandociencia.com/tag/python/.
Thanks!

**Comment by rochacbruno** [comment]
Hi @alexandrejaguar I used the /english/feed because english only posts fits better with Python Planet international.

Should be online in few hours in the next server update.

**Comment by alexandrejaguar** [comment]
Hi @rochacbruno,
thanks! I owe you a beer!
