### ISSUE TITLE
Request to add my blog to planet python

### ISSUE THREAD

**Issue by saisrk** [python/planet#91]
Name: S.R.Krishnan
Blog: pyhelper.wordpress.com

**Comment by tseaver** [comment]
Can you please give us the URL for the Atom / RSS 2.0 feed?

**Comment by saisrk** [comment]
Feed URL: https://pyhelper.wordpress.com/feed/

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle (an hour or two).

**Comment by saisrk** [comment]
Thank you very much
