### ISSUE TITLE
Odoo Community Association

### ISSUE THREAD

**Issue by jbradberry** [python/planet#97]
is apparently dynamically setting the timestamps on the articles in its feed, causing their article(s) to rise to the top of the Planet Python page every day.

**Comment by tseaver** [comment]
@max3903 can you please address this issue quickly?  If not, I will need to back out de3446fc1a53e8a170955ea0f9ebcf65f1ed22fa (which closed #96).

**Comment by tseaver** [comment]
@alpaca-power looks like the Codementor feed (added in b3a6bd09f16bcb933b3fd3a51343546de586ddf3 to close #62) has the same issue.  Please address ASAP, or I will need to back out that commit.

**Comment by max3903** [comment]
@tseaver I am on it. Sorry for the inconvenience.

**Comment by alpaca-power** [comment]
@tseaver We're looking into this, sorry about that.

**Comment by godfat** [comment]
@tseaver I am sorry, but could you please explain what date was wrong? For now, Codementor feed's `updated` timestamp was set to `published` of the first post, and I believe `published` is not changing at all.

**Comment by tseaver** [comment]
@godfat I believe I was in error:  the post, "The Script that Saved My Sanity" showed up stamped at exactly the same time as the two posts from Odoo Community Association.  Looking at the feed XML:

```xml
    <title type="html">The Script that Saved My Sanity</title>
    <link rel="alternate" href="https://www.codementor.io/python/tutorial/no-wifi-signal-macbook-the-script-that-saved-my-sanity"/>
    <id>tag:www.codementor.io,2014:tutorial:828</id>
    <updated>2016-01-07T13:46:19Z</updated>
    <published>2016-01-04T09:12:11Z</published>
```

It appears correctly rendered.

**Comment by godfat** [comment]
Alright, thanks for checking.

**Comment by aroberge** [comment]
I thought that PlanetPython was for Python specific content which could be of interest to an average Python programmer ... Perhaps it is just me ... but I have yet to see anything of interest to a typical Python programmer in the annoyingly long posts from Odoo community association.

**Comment by ajilius** [comment]
Please, make them go away.

**Comment by ajilius** [comment]
Oh, please make it go away. Every time I come to PlanetPython it is full of Odoo. Now I'm seeing old posts all over again. I've been reading PlanetPython for 12 months now, and never before have I been bombarded by crap like we're getting now.

**Comment by malemburg** [comment]
Something is clearly wrong, e.g. this post: https://odoo-community.org/blog/oca-news-1/post/2016-wishes-planet-python-reddit-packaging-and-runbots-34 shows up on the planet with timestamp "January 11, 2016 10:23 AM", while the blog itself uses "05 January 2016".

**Comment by malemburg** [comment]
The RSS feed () shows this as:
```
            <item>
                <title>2016 Wishes, Planet Python, Reddit, Packaging and Runbots</title>
                <link>http://odoo-community.org/blog/oca-news-1/post/2016-wishes-planet-python-reddit-packaging-and-runbots-34</link>
                <guid>http://odoo-community.org/blog/oca-news-1/post/2016-wishes-planet-python-reddit-packaging-and-runbots-34</guid>
                <pubDate>Mon, 11 Jan 2016 11:17:10 -0000</pubDate>
```
so it's clearly the blog that's not working correctly here.

PS: I also think posts should be limited in length to prevent excessively long posts as the one above from cluttering up the feed. Not sure whether the planet software allows for this, though.

**Comment by tjguk** [comment]
Ok; I'm going to temporarily remove the OCA feed from Planet Python
while we agree what needs to happen further: it's consistently coming at
the top of the page with very long posts which are, at best, only
tangentially related to Python.

**Comment by tjguk** [comment]
@max3903 I think what we're looking for is: the correct pubDate so the articles don't always show at the top; article summaries rather than full text (if they're going to be that long); ideally a category feed which would interest Python users rather than simply users of your system.

**Comment by max3903** [comment]
@tjguk I understand. And as I said in my first comment, it is currently taken care of:
Vauxoo/addons-vauxoo#619

**Comment by tjguk** [comment]
Thanks @max3903; look forward to jhearing back from you
