### ISSUE TITLE
Request to update my feed URL

### ISSUE THREAD

**Issue by ajdavis** [python/planet#99]
Hi, I've recently moved hosts and unfortunately my blog no longer supports HTTPS. Could you please update my feed, which is currently this?:

```
https://emptysqua.re/blog/category/python/feed
```

To this?:

```
http://emptysqua.re/blog/category/python/feed/
```

Thanks!

**Comment by tjguk** [comment]
It appears to be set to that already.

**Comment by ajdavis** [comment]
Hi Tim! No, I don't think the URL is correctly set in Planet Python. I have two bits of evidence:

1. My blog post "This Site Is Built With Lektor", updated 2016-01-10T13:48:20Z, doesn't appear in http://planetpython.org/rss20.xml, although entries of other people's blogs before and after that date do appear in the Planet Python feed.
2. In http://planetpython.org/opml.xml, the URL for my feed is https://emptysqua.re/blog/category/python/feed (wrong) instead of http://emptysqua.re/blog/category/python/feed/ (correct).

Thanks.

**Comment by rochacbruno** [comment]
Hi @ajdavis the entry currently is https://github.com/python/planet/blob/master/config/config.ini#L588

```
[http://emptysqua.re/blog/category/python/feed]
name = A. Jesse Jiryu Davis
```
Do you think the problem is the missing trailing slash?

**Comment by ajdavis** [comment]
Oh I bet the missing slash is the problem! Could you add the slash please?
